// flow-typed signature: 2754da8bae8ff2dc1dbb6c1888fca0fd
// flow-typed version: <<STUB>>/flow-immutable-models_v^0.11.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-immutable-models'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-immutable-models' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-immutable-models/lib/createModelClass' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/capitalize' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/flowTypes' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/fromImmutable' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/fromJS' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/getNonClassTypes' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/getReferenceProps' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/getter' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/getTypeAnnotationWithoutModelType' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/initialize' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/isImmutableType' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/isModelTypeReference' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/setter' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/toJS' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/typeToExpression' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/helpers/withoutModelTypeSuffix' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/ImmutableModel' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/test-utils/transformFixture' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/lib/transform' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/capitalize' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/flowTypes' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/fromImmutable' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/fromJS' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/getNonClassTypes' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/getter' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/getTypeAnnotationWithoutModelType' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/initialize' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/isModelTypeReference' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/setter' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/toJS' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/typeToExpression' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/helpers/withoutModelTypeSuffix' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/ImmutableModel' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/test-utils/transformFixture' {
  declare module.exports: any;
}

declare module 'flow-immutable-models/src/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-immutable-models/lib/createModelClass.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/createModelClass'>;
}
declare module 'flow-immutable-models/lib/helpers/capitalize.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/capitalize'>;
}
declare module 'flow-immutable-models/lib/helpers/flowTypes.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/flowTypes'>;
}
declare module 'flow-immutable-models/lib/helpers/fromImmutable.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/fromImmutable'>;
}
declare module 'flow-immutable-models/lib/helpers/fromJS.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/fromJS'>;
}
declare module 'flow-immutable-models/lib/helpers/getNonClassTypes.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/getNonClassTypes'>;
}
declare module 'flow-immutable-models/lib/helpers/getReferenceProps.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/getReferenceProps'>;
}
declare module 'flow-immutable-models/lib/helpers/getter.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/getter'>;
}
declare module 'flow-immutable-models/lib/helpers/getTypeAnnotationWithoutModelType.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/getTypeAnnotationWithoutModelType'>;
}
declare module 'flow-immutable-models/lib/helpers/initialize.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/initialize'>;
}
declare module 'flow-immutable-models/lib/helpers/isImmutableType.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/isImmutableType'>;
}
declare module 'flow-immutable-models/lib/helpers/isModelTypeReference.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/isModelTypeReference'>;
}
declare module 'flow-immutable-models/lib/helpers/setter.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/setter'>;
}
declare module 'flow-immutable-models/lib/helpers/toJS.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/toJS'>;
}
declare module 'flow-immutable-models/lib/helpers/typeToExpression.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/typeToExpression'>;
}
declare module 'flow-immutable-models/lib/helpers/withoutModelTypeSuffix.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/helpers/withoutModelTypeSuffix'>;
}
declare module 'flow-immutable-models/lib/ImmutableModel.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/ImmutableModel'>;
}
declare module 'flow-immutable-models/lib/test-utils/transformFixture.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/test-utils/transformFixture'>;
}
declare module 'flow-immutable-models/lib/transform.js' {
  declare module.exports: $Exports<'flow-immutable-models/lib/transform'>;
}
declare module 'flow-immutable-models/src/helpers/capitalize.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/capitalize'>;
}
declare module 'flow-immutable-models/src/helpers/flowTypes.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/flowTypes'>;
}
declare module 'flow-immutable-models/src/helpers/fromImmutable.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/fromImmutable'>;
}
declare module 'flow-immutable-models/src/helpers/fromJS.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/fromJS'>;
}
declare module 'flow-immutable-models/src/helpers/getNonClassTypes.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/getNonClassTypes'>;
}
declare module 'flow-immutable-models/src/helpers/getter.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/getter'>;
}
declare module 'flow-immutable-models/src/helpers/getTypeAnnotationWithoutModelType.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/getTypeAnnotationWithoutModelType'>;
}
declare module 'flow-immutable-models/src/helpers/initialize.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/initialize'>;
}
declare module 'flow-immutable-models/src/helpers/isModelTypeReference.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/isModelTypeReference'>;
}
declare module 'flow-immutable-models/src/helpers/setter.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/setter'>;
}
declare module 'flow-immutable-models/src/helpers/toJS.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/toJS'>;
}
declare module 'flow-immutable-models/src/helpers/typeToExpression.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/typeToExpression'>;
}
declare module 'flow-immutable-models/src/helpers/withoutModelTypeSuffix.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/helpers/withoutModelTypeSuffix'>;
}
declare module 'flow-immutable-models/src/ImmutableModel.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/ImmutableModel'>;
}
declare module 'flow-immutable-models/src/test-utils/transformFixture.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/test-utils/transformFixture'>;
}
declare module 'flow-immutable-models/src/transform.js' {
  declare module.exports: $Exports<'flow-immutable-models/src/transform'>;
}
