// Code generated by 'github.com/shabbyrobe/go-enumgen'. DO NOT EDIT.

package lfclient

import "fmt"

func (v IssueState) Name() string {
	switch v {
	case Admission:
		return "Admission"
	case Discussion:
		return "Discussion"
	case Idle:
		return "Idle"
	case Verification:
		return "Verification"
	case Voting:
		return "Voting"
	default:
		return ""
	}
}

func (v IssueState) Lookup(name string) (value IssueState, ok bool) {
	switch name {
	case "Admission":
		return Admission, true
	case "Discussion":
		return Discussion, true
	case "Idle":
		return Idle, true
	case "Verification":
		return Verification, true
	case "Voting":
		return Voting, true
	default:
		return "", false
	}
}

func (v IssueState) IsValid() bool {
	switch v {
	case Admission:
	case Discussion:
	case Idle:
	case Verification:
	case Voting:
	default:
		return false
	}
	return true
}

func (v IssueState) String() string {
	switch v {
	case Admission:
		return "admission"
	case Discussion:
		return "discussion"
	case Idle:
		return "idle"
	case Verification:
		return "verification"
	case Voting:
		return "voting"
	default:
		return "<unknown>"
	}
}

func (v *IssueState) Set(s string) error {
	*v = IssueState(s)
	if !v.IsValid() {
		return fmt.Errorf("enum %T received invalid value %q", v, s)
	}
	return nil
}
