#!/bin/bash
set -o errexit -o nounset -o pipefail

# Workingdirection is rooset base dir
SCRIPTDIR=`dirname "$(readlink -f "$0")"`
cd ${SCRIPTDIR}

export CI=true # jest should run in non-interactive mode

${SCRIPTDIR}/scripts/generate
npm run flow
npm run test
