#!/bin/bash
set -o errexit -o nounset -o pipefail

WORKDIR=`dirname "$(readlink -f "$0")"`
cd $WORKDIR

source ${WORKDIR}/../etc/set-env

${WORKDIR}/../rooset-application-toolkit/languages/js/tools/generate-js-query-tests
