version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "9443:443"
      - "9080:80"
      - "9022:22"
    volumes:
      - "./volumes/gitlab/config:/etc/gitlab"
      - "./volumes/gitlab/logs:/var/log/gitlab"
      - "./volumes/gitlab/data:/var/opt/gitlab"

  webhook_logger:
    build:
      context: ./log-server/
    command: "node index.js"


