---
version: "3.3"
services:
  webhook_logger:
    build:
      context: ./log-server/
    command: "node index.js"

  db:
    image: postgres:12
    volumes:
      - './volumes/db:/var/lib/postgresql/data'

  lfcore:
    build:
      context: .
      dockerfile: core.Dockerfile
    links:
      - db
    env_file:
      - conf/dockerdev.env
    entrypoint: /usr/local/bin/keep-alive
    volumes:
      - ./lfcore:/opt/lfcore
      - ./etc:/opt/etc

  lffrontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - conf/dockerdev.env
    ports:
      - "8081:8080"
    links:
      - db
    volumes:
      - ./lffrontend:/opt/frontend
      - ./lfframework:/opt/framework
      - ./etc:/opt/etc
    entrypoint: /usr/local/bin/keep-alive

  webpack:
    image: node:erbium-stretch
    volumes:
      - .:/go/src/github.com/ddouglascarr/rooset
    working_dir: /go/src/github.com/ddouglascarr/rooset
    command: 'bash -c "npm install && npm run start"'
    ports:
      - "8082:8080"

  docsvc:
    build:
      context: .
      dockerfile: docsvc.Dockerfile
    env_file:
      - conf/dockerdev.env
    volumes:
      - .:/go/src/github.com/ddouglascarr/rooset
      - ./volumes/blobs/:/var/lib/docsvc/blobs/
    working_dir: /go/src/github.com/ddouglascarr/rooset
    # command: go run cmd/rooset.go docsvc
    command: /go/src/github.com/ddouglascarr/rooset/etc/keep-alive
    ports:
      - "8084:8080"
