---
version: "3.3"
services:
  webhook_logger:
    build:
      context: ./log-server/
    command: "node index.js"

  db:
    image: postgres:12
    volumes:
      - './volumes/db:/var/lib/postgresql/data'

  lfcore:
    build:
      context: .
      dockerfile: lf.Dockerfile
    links:
      - db
    env_file:
      - conf/dockerdev.env
    entrypoint: /opt/rooset/etc/keep-alive
    volumes:
      - ./lfcore:/opt/rooset/lfcore
      - ./etc:/opt/rooset/etc

  lffrontend:
    build:
      context: .
      dockerfile: lf.Dockerfile
    env_file:
      - conf/dockerdev.env
    ports:
      - "8081:8080"
    links:
      - db
    volumes:
      # dont just use ., as lfmoonbridge needs to be compiled in place
      - ./etc:/opt/rooset/etc
      - ./lfframework:/opt/rooset/lfframework
      - ./lffrontend:/opt/rooset/lffrontend
      - ./lfcore:/opt/rooset/lfcore
    entrypoint: /opt/rooset/etc/keep-alive

  webpack:
    image: node:erbium-stretch
    volumes:
      - .:/go/src/github.com/ddouglascarr/rooset
    working_dir: /go/src/github.com/ddouglascarr/rooset
    command: 'bash -c "npm install && npm run start"'
    ports:
      - "8082:8080"

  docsvc:
    build:
      context: .
      dockerfile: docsvc.Dockerfile
    env_file:
      - conf/dockerdev.env
    volumes:
      - .:/go/src/github.com/ddouglascarr/rooset
      - ./volumes/blobs/:/var/lib/docsvc/blobs/
    working_dir: /go/src/github.com/ddouglascarr/rooset
    command: go run cmd/rooset.go docsvc
    # command: /go/src/github.com/ddouglascarr/rooset/etc/keep-alive
    ports:
      - "8084:8080"
