---
version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "9443:443"
      - "9080:80"
      - "9022:22"
    volumes:
      - "./volumes/gitlab/config:/etc/gitlab"
      - "./volumes/gitlab/logs:/var/log/gitlab"
      - "./volumes/gitlab/data:/var/opt/gitlab"

  webhook_logger:
    build:
      context: ./log-server/
    command: "node index.js"

  db:
    image: postgres:12
    volumes:
      - './volumes/db:/var/lib/postgresql/data'

  lfcore:
    build:
      context: .
      dockerfile: core.Dockerfile
    links:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=liquid_feedback
      - CORE_SERVICES_INITIAL_DELAY=1
      - CORE_SERVICES_REPEAT_DELAY=3
    entrypoint: /usr/local/bin/keep-alive
    volumes:
      - ./lfcore:/opt/lfcore
      - ./etc:/opt/etc
