server:
  port: 8095

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      'ddl-auto': validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://${ROOSET_RDB_HOST}:${ROOSET_RDB_PORT}/rooset_http_api
    username: rooset
    password: rooset
    driverClassName: org.postgresql.Driver
    tomcat:
      'max-active': 5
      'max-wait': 10000

rooset:
  'domain-command-bin': '@basedir@/../rooset-domain-command-posix/build/rooset-command'

get-event-store:
  port: ${ROOSET_EVENT_STORE_PORT}
  host: ${ROOSET_EVENT_STORE_HOST}
  binPath: '' # Not used in production, testing only


---

spring:
  profiles: clean-dev
  jpa:
    'show-sql': true
    hibernate:
      'ddl-auto': create-drop
  datasource:
    url: jdbc:postgresql://${ROOSET_RDB_HOST}:${ROOSET_RDB_PORT}/rooset_http_api_testing


---

spring:
  profiles: integration-tests
  jpa:
    'show-sql': true
    hibernate:
      'ddl-auto': create-drop
  datasource:
    url: jdbc:postgresql://${ROOSET_RDB_HOST}:${ROOSET_RDB_PORT}/rooset_http_api_integration_testing


get-event-store:
  port: ${ROOSET_EVENT_STORE_PORT}
  host: ${ROOSET_EVENT_STORE_HOST}
  binPath: '/opt/EventStore'
  'init-all-projections-bin': '@basedir@/../rooset-domain-query-reducers/init-all-projections'
