server:
  port: 8095

spring:
  jpa:
    database: POSTGRESQL
    'show-sql': true
    hibernate:
      'ddl-auto': create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rooset_http_api
    username: daniel
    password: daniel
    driveClassName: org.postgresql.Driver

rooset:
  'domain-command-bin': '@basedir@/../rooset-domain-command-posix/build/rooset-command'

get-event-store:
  port: 2113
  host: localhost

---

spring:
  profiles: integration-tests

get-event-store:
  port: 2114
  host: localhost
  bin: /home/daniel/opt/EventStore-OSS-Ubuntu-14.04-v3.9.3/run-node.sh

