#!/bin/bash
set -o errexit -o nounset -o pipefail


########################################
#
# Rough tool for persisting a test precondition to
# EventStore. Don't use this in formal tests. It
# is for manual testing an experimentation.
#
# Usage: ./persist-test-precondition <test-key> <precondition-key>
# Example: ./persist-test-precondition area-issue-delegation-command area-created
#
########################################


WORKDIR=`dirname "$(readlink -f "$0")"`
cd $WORKDIR

export RATK_GEN_TEST_DECL_DIR=${WORKDIR}/../../rooset-declarations/src/tests
echo $RATK_GEN_TEST_DECL_DIR

curlCommands=$(node -e "require('./src/generateCurlCommands')('$1', '$2')")

eval "${curlCommands}"
