#!/bin/bash
set -o errexit -o nounset -o pipefail

WORKDIR=`dirname "$(readlink -f "$0")"`
cd $WORKDIR

export RATK_GEN_TEST_DECL_DIR=${WORKDIR}/../../rooset-declarations/src/tests
echo $RATK_GEN_TEST_DECL_DIR

curlCommands=$(node -e "require('./src/generateCurlCommands')('$1', '$2')")

eval "${curlCommands}"
