#!/bin/bash

SCRIPTDIR=`dirname "$(readlink -f "$0")"`
export RATK_GEN_QUERY_ACTION_JS_DEST_DIR="${SCRIPTDIR}/../src/actions/http"
export RATK_GEN_QUERY_DECL_DIR="${SCRIPTDIR}/../../rooset-declarations/src/queries"

${SCRIPTDIR}/../../rooset-application-toolkit/languages/js/tools/generate-js-query-actions
