#!/bin/bash
set -o errexit -o nounset -o pipefail
# You need postgresql and eventstore running-tests
# To run an in-memory eventstore:
# eventstored --run-projections=all --mem-db

SCRIPTDIR=`dirname "$(readlink -f "$0")"`

${SCRIPTDIR}/../../rooset-domain-query-reducers/init-all-projections
${SCRIPTDIR}/../../rooset-application-toolkit/tools/persist-test-precondition \
  area-issue-delegation-command area-created

cd ${SCRIPTDIR}/../../rooset-http-api
mvn spring-boot:run -Drun.profiles=clean-dev
