#!/bin/bash
set -o errexit -o nounset -o pipefail

SCRIPTDIR=`dirname "$(readlink -f "$0")"`
ROOSETDIR=${SCRIPTDIR}/..
cd ${SCRIPTDIR}

source ${ROOSETDIR}/etc/set-env

# set up test database and user if it doesnt exist
if [[ -z `psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='rooset'"` ]]; then
  echo "creating user rooset"
  createuser -U ${ROOSET_RDB_SUPERUSER} rooset
  psql -U ${ROOSET_RDB_SUPERUSER} -c "ALTER USER rooset WITH PASSWORD 'rooset';"
fi

if [[ -z `psql -Atqc '\list rooset_http_api_integration_test' postgres` ]]; then
  createdb -U ${ROOSET_RDB_SUPERUSER} --owner=rooset rooset_http_api_integration_test;
fi

mvn test
