#!/bin/bash

export PGDATABASE=rooset_test

lua \
  /opt/rooset/lfframework/framework/bin/mcp.lua \
  /opt/rooset/lfframework/framework/ \
  /opt/rooset/lffrontend/ \
  main \
  ${FRONTEND_CONFIG} \
  /opt/rooset/lffrontend/test/do_tests.lua
