#!/bin/bash
set -euo pipefail

################################################################################
#
# reset-integration-test-dbs
#
# resets the integration tests databases. needs to be run before integration 
# tests
#
# e.g.
#
#   $ . etc/set-env
#   $ etc/reset-integration-test-dbs
#   $ go test -tags=integration ./...
#
################################################################################

SCRIPT_DIR="${BASH_SOURCE%/*}"
export PGPORT=${ROOSET_INTEGRATION_TEST_PORT}

${SCRIPT_DIR}/reset-dbs
