#!/bin/bash
set -euo pipefail

################################################################################
#
# reset-dbs
#
# Resets the Rooset test databases. This will delete all data in those 
# databases.
#
# e.g.
#   
#   $ . etc/set-env
#   $ etc/reset-dbs
#
################################################################################

SCRIPT_DIR="${BASH_SOURCE%/*}"

echo "--- resting cmd db"
dropdb --if-exists ${ROOSET_CMD_DB}
createdb ${ROOSET_CMD_DB}
psql -v ON_ERROR_STOP=1 -f ${SCRIPT_DIR}/../storage/schema/schema.sql ${ROOSET_CMD_DB}

echo "--- resting query db"
dropdb --if-exists ${ROOSET_QUERY_DB}
createdb ${ROOSET_QUERY_DB}
psql -v ON_ERROR_STOP=1 -f ${SCRIPT_DIR}/../storage/schema/schema.sql ${ROOSET_QUERY_DB}



