#!/bin/bash
WORKDIR=`dirname "$(readlink -f "${BASH_SOURCE[0]}")"`

# use node 7.10
if type "nvm" > /dev/null; then
  nvm use 7.10
fi

export ROOSET_BASE_DIR=${WORKDIR}/..

export ROOSET_RDB_HOST="${ROOSET_RDB_HOST:-localhost}"
export ROOSET_RDB_PORT="${ROOSET_RDB_PORT:-5432}"
export ROOSET_RDB_SUPERUSER="${ROOSET_RDB_SUPERUSER:-postgres}"
export ROOSET_EVENT_STORE_HOST="${ROOSET_EVENT_STORE_HOST:-localhost}"
export ROOSET_EVENT_STORE_PORT="${ROOSET_EVENT_STORE_PORT:-2113}"
export ROOSET_SEARCH_HOST="${ROOSET_SEARCH_HOST:-localhost}"
export ROOSET_SEARCH_HTTP_PORT="${ROOSET_SEARCH_HTTP_PORT:-9200}"
export ROOSET_SEARCH_TCP_PORT="${ROOSET_SEARCH_TCP_PORT:-9300}"

export RATK_BASE_DIR=${ROOSET_BASE_DIR}/gen
export RATK_DECL_BASE_DIR=${ROOSET_BASE_DIR}/rooset-declarations/src
export RATK_GEN_BASE_SCHEMA_FILE=${WORKDIR}/../rooset-declarations/src/base.schema.json

export RATK_DECL_COMMAND_DIR=${RATK_DECL_BASE_DIR}/commands
export RATK_DECL_EVENT_DIR=${RATK_DECL_BASE_DIR}/events
export RATK_DECL_EXCEPTION_DIR=${RATK_DECL_BASE_DIR}/exceptions
export RATK_DECL_TEST_DIR=${WORKDIR}/../rooset-declarations/src/tests
export RATK_DECL_QUERY_DIR=${WORKDIR}/../rooset-declarations/src/queries
export RATK_QUERY_REDUCER_SRC_DIR=${WORKDIR}/reducers

export RATK_CPP_TOOLS_DIR=${ROOSET_BASE_DIR}/rooset-application-toolkit/languages/cpp/tools
export RATK_CPP_DIR=${RATK_BASE_DIR}/cpp
export RATK_CPP_COMMAND_DIR=${RATK_CPP_DIR}/commands
export RATK_CPP_EVENT_DIR=${RATK_CPP_DIR}/events
export RATK_CPP_ENUM_DIR=${RATK_CPP_DIR}/enums
export RATK_CPP_EXCEPTION_DIR=${RATK_CPP_DIR}/exceptions
export RATK_CPP_TEST_DIR=${RATK_CPP_DIR}/tests

export RATK_JS_DIR=${RATK_BASE_DIR}/js
export RATK_JS_TOOLS_DIR=${ROOSET_BASE_DIR}/rooset-application-toolkit/languages/js/tools
export RATK_JS_TEST_QUERY_DIR=${ROOSET_BASE_DIR}/rooset-domain-query-reducers/__tests__
export RATK_JS_QUERY_ACTION_DIR="${RATK_JS_DIR}/query-actions"

# PS1="(rooset) ${PS1}"
