#!/bin/bash
set -euo pipefail

################################################################################
#
# setup-test-scenario-0
#
# Sets up a dev scenario on a Rooset database. This will delete all
# data currently in that database. Use it for manual testing.
#
# Requires a Postgres database on localhost:5433
#
# e.g.
#
#  $ . etc/set-env
#  $ etc/setup-test-scenario-0
#
################################################################################

SCRIPT_DIR="${BASH_SOURCE%/*}"

echo "--- Installing roosetdev"
go install github.com/ddouglascarr/rooset/cmd/roosetdev

${SCRIPT_DIR}/reset-dbs

echo "--- Creating Test Unit"
roosetdev exec '{
  "MessageType": "messages.CreateUnitCmd",
  "Message": {
    "UnitID": "unit0",
    "RequesterID": "user0",
    "Name": "Test Unit",
    "Description": "The Test Unit",
    "URLParameterName": "test-unit"
  }
}'

echo "--- Creating Test Area"
roosetdev exec '{
  "MessageType": "messages.CreateAreaCmd",
  "Message": {
    "UnitID": "unit0",
    "RequesterID": "user0",
    "AreaID": "area0",
    "Name": "Test Area 0",
    "Description": "The Test Area Number 0"
  }
}'

echo "--- Creating Test Policy"
roosetdev exec '{
  "MessageType": "messages.CreatePolicyCmd",
  "Message": {
    "UnitID": "unit0",
    "RequesterID": "user0",
    "PolicyID": "policy0",
    "Description": "Test Policy",
    "MinAdmissionDuration": 10000,
    "MaxAdmissionDuration": 3600000,
    "DiscussionDuration": 3600000,
    "VerificationDuration": 3600000,
    "VotingDuration": 3600000,
    "IssueQuorumNum": 1,
    "IssueQuorumDen": 10,
    "InitiativeQuorumNum": 2,
    "InitiativeQuorumDen": 10 
  }
}'
