#!/bin/bash
set -eou pipefail

################################################################################
# 
# Starts a clean Rooset system for testing. 
# All data will be lost on exit
#
################################################################################

SCRIPTDIR=`dirname "$(readlink -f "$0")"`
cd $SCRIPTDIR

EVENTSTORE_LOG_FILE="/tmp/rooset-testing-eventstore.log"
EVENTSTORE_READY_LINE="Sub System 'Projections' initialized"
ELASTICSTORE_READY_LINE="success"

# Kill all processes on exit
killAllJobs () {
  echo "killing processes: $(jobs -p)"
  kill $(jobs -p)
  exit 0
}
trap killAllJobs EXIT

waitForLogToHaveLine () {
  log_file=$1
  ready_line=$2
  echo "waiting for \"${ready_line}\" in ${log_file}"
  ( tail --pid=$$ -f ${log_file} & ) | grep -q "${ready_line}"
}


# Start eventstore with in-memory database
echo "starting eventstore"
eventstored --mem-db --run-projections=all 2>&1 > ${EVENTSTORE_LOG_FILE} &
echo "eventstore started with pid: ${!}"
waitForLogToHaveLine ${EVENTSTORE_LOG_FILE} "${EVENTSTORE_READY_LINE}"
echo "eventstore ready"


# Start elasticsearch with a fresh database
#(
#  ${SCRIPTDIR}/start-test-elasticsearch &
#  elasticsearch_pid=$!
#) | tee -a ${LOG_FILE} | grep -q "${ELASTICSEARCH_READY_LINE}"
# echo "elasticsearch started with pid: ${elasticsearch_pid}"

# Keep script alive
while true; do sleep 5; done

