#!/bin/bash
set -o errexit -o nounset -o pipefail

###############################################################################
#
# Runs elasticsearch with a clean database for testing
# Any previous database files are deleted before running.
#
###############################################################################
SCRIPTDIR=`dirname "$(readlink -f "$0")"`
cd $SCRIPTDIR

ELASTICSEARCH_BIN=/usr/share/elasticsearch/bin/elasticsearch
ES_HOME=/usr/share/elasticsearch
CONF_DIR=${SCRIPTDIR}/elasticsearch-testing
DATA_DIR=/tmp/elasticsearch-testing
LOG_DIR=/tmp/log/elasticsearch-testing
PID_FILE=/tmp/elasticsearch-testing.pid

# elasticsearch is weird, needs killing like this.
killElasticsearch () {
  echo "killing elasticsearch $(cat ${PID_FILE})"
  kill -SIGTERM $(cat ${PID_FILE})
}
trap killElasticsearch EXIT


$(rm -r ${DATA_DIR} &> /dev/null || true)
mkdir -p ${DATA_DIR}
mkdir -p ${LOG_DIR}

${ELASTICSEARCH_BIN} \
  -p ${PID_FILE} \
  -Edefault.path.logs=${LOG_DIR} \
  -Edefault.path.data=${DATA_DIR} \
  -Edefault.path.conf=${CONF_DIR} 2>&1 &

while true; do sleep 1; done

