#!/bin/bash
set -o errexit -o nounset -o pipefail

# Workingdirection is rooset base dir
SCRIPTDIR=`dirname "$(readlink -f "$0")"`
WORKDIR=${SCRIPTDIR}/build
mkdir -p ${WORKDIR}
cd ${WORKDIR}

make
./rooset-unit-tests
./rooset-generated-tests
make test
