// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/app.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	CSRFTk               string   `protobuf:"bytes,3,opt,name=CSRFTk,proto3" json:"CSRFTk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_9a3cbccdfa07bbc8, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Session) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Session) GetCSRFTk() string {
	if m != nil {
		return m.CSRFTk
	}
	return ""
}

func init() {
	proto.RegisterType((*Session)(nil), "messages.Session")
}

func init() { proto.RegisterFile("messages/app.proto", fileDescriptor_app_9a3cbccdfa07bbc8) }

var fileDescriptor_app_9a3cbccdfa07bbc8 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0x2c, 0x28, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x80, 0x89, 0x29, 0x85, 0x72, 0xb1, 0x07, 0xa7, 0x16, 0x17, 0x67, 0xe6, 0xe7, 0x09, 0x89, 0x71,
	0xb1, 0x85, 0x16, 0xa7, 0x16, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79,
	0x42, 0x52, 0x5c, 0x1c, 0x20, 0x56, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x06, 0xce, 0x07,
	0xe9, 0x71, 0x0e, 0x0e, 0x72, 0x0b, 0xc9, 0x96, 0x60, 0x86, 0xe8, 0x81, 0xf0, 0x92, 0xd8, 0xc0,
	0xf6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40, 0x26, 0x4c, 0xe3, 0x7d, 0x00, 0x00, 0x00,
}
