// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/commands.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUnitCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitCommand) Reset()         { *m = CreateUnitCommand{} }
func (m *CreateUnitCommand) String() string { return proto.CompactTextString(m) }
func (*CreateUnitCommand) ProtoMessage()    {}
func (*CreateUnitCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_1bcfd788911c08b4, []int{0}
}
func (m *CreateUnitCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitCommand.Unmarshal(m, b)
}
func (m *CreateUnitCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitCommand.Marshal(b, m, deterministic)
}
func (dst *CreateUnitCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitCommand.Merge(dst, src)
}
func (m *CreateUnitCommand) XXX_Size() int {
	return xxx_messageInfo_CreateUnitCommand.Size(m)
}
func (m *CreateUnitCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitCommand proto.InternalMessageInfo

func (m *CreateUnitCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateUnitCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateUnitCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUnitCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUnitCommand) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type GrantPrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	PollingRight         bool     `protobuf:"varint,4,opt,name=PollingRight,proto3" json:"PollingRight,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPrivilegeCommand) Reset()         { *m = GrantPrivilegeCommand{} }
func (m *GrantPrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*GrantPrivilegeCommand) ProtoMessage()    {}
func (*GrantPrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_1bcfd788911c08b4, []int{1}
}
func (m *GrantPrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPrivilegeCommand.Unmarshal(m, b)
}
func (m *GrantPrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *GrantPrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPrivilegeCommand.Merge(dst, src)
}
func (m *GrantPrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_GrantPrivilegeCommand.Size(m)
}
func (m *GrantPrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPrivilegeCommand proto.InternalMessageInfo

func (m *GrantPrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetPollingRight() bool {
	if m != nil {
		return m.PollingRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type RevokePrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	Weight               uint32   `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePrivilegeCommand) Reset()         { *m = RevokePrivilegeCommand{} }
func (m *RevokePrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*RevokePrivilegeCommand) ProtoMessage()    {}
func (*RevokePrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_1bcfd788911c08b4, []int{2}
}
func (m *RevokePrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePrivilegeCommand.Unmarshal(m, b)
}
func (m *RevokePrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *RevokePrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePrivilegeCommand.Merge(dst, src)
}
func (m *RevokePrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_RevokePrivilegeCommand.Size(m)
}
func (m *RevokePrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePrivilegeCommand proto.InternalMessageInfo

func (m *RevokePrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateUnitCommand)(nil), "messages.CreateUnitCommand")
	proto.RegisterType((*GrantPrivilegeCommand)(nil), "messages.GrantPrivilegeCommand")
	proto.RegisterType((*RevokePrivilegeCommand)(nil), "messages.RevokePrivilegeCommand")
}

func init() { proto.RegisterFile("messages/commands.proto", fileDescriptor_commands_1bcfd788911c08b4) }

var fileDescriptor_commands_1bcfd788911c08b4 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xc1, 0x4e, 0x32, 0x31,
	0x14, 0x85, 0x33, 0xfc, 0xc0, 0x3f, 0x5e, 0x35, 0x6a, 0x13, 0x71, 0x24, 0x2e, 0x08, 0x2b, 0xe2,
	0x42, 0x17, 0xee, 0xdc, 0x42, 0x62, 0x48, 0xc4, 0x90, 0x26, 0xe8, 0xd2, 0x14, 0xbc, 0x8e, 0x8d,
	0xd3, 0x16, 0xdb, 0x0b, 0x0f, 0xe0, 0x23, 0xb8, 0xf4, 0x15, 0x7c, 0x04, 0x5f, 0xce, 0x4c, 0x3b,
	0xc0, 0x80, 0x71, 0x65, 0xe2, 0x6e, 0xce, 0x39, 0x5f, 0x3b, 0xf7, 0xdc, 0x14, 0x8e, 0x14, 0x3a,
	0x27, 0x52, 0x74, 0xe7, 0x13, 0xa3, 0x94, 0xd0, 0x0f, 0xee, 0x6c, 0x6a, 0x0d, 0x19, 0x16, 0x2f,
	0x82, 0xe6, 0xc9, 0x0a, 0x99, 0x39, 0x32, 0xea, 0xfe, 0x51, 0x62, 0xb6, 0xe0, 0xda, 0x9f, 0x11,
	0x1c, 0x74, 0x2d, 0x0a, 0xc2, 0x91, 0x96, 0xd4, 0x0d, 0x97, 0xb0, 0x06, 0xd4, 0x73, 0xd9, 0xef,
	0x25, 0x51, 0x2b, 0xea, 0x6c, 0xf1, 0x42, 0xb1, 0x16, 0x6c, 0x73, 0x7c, 0x99, 0xa1, 0x23, 0xb4,
	0xfd, 0x5e, 0x52, 0xf1, 0x61, 0xd9, 0x62, 0x0c, 0xaa, 0x37, 0x42, 0x61, 0xf2, 0xcf, 0x47, 0xfe,
	0x3b, 0x3f, 0xd5, 0x43, 0x37, 0xb1, 0x72, 0x4a, 0xd2, 0xe8, 0xa4, 0x1a, 0x4e, 0x95, 0x2c, 0x76,
	0x0a, 0xfb, 0x23, 0x7e, 0x3d, 0x14, 0x56, 0x28, 0x24, 0xb4, 0xfe, 0x86, 0x9a, 0xc7, 0xbe, 0xf9,
	0x97, 0xf0, 0xfe, 0x7a, 0x5c, 0xcc, 0xd3, 0xfe, 0xa8, 0xc0, 0xe1, 0x95, 0x15, 0x9a, 0x86, 0x56,
	0xce, 0x65, 0x86, 0x29, 0xfe, 0xbe, 0x41, 0x13, 0xe2, 0x01, 0xaa, 0xb1, 0x8f, 0x43, 0x8b, 0xa5,
	0x66, 0x6d, 0xd8, 0x19, 0x9a, 0x2c, 0x93, 0x3a, 0xe5, 0x32, 0x7d, 0x22, 0x5f, 0x25, 0xe6, 0x6b,
	0x5e, 0xfe, 0x87, 0x5b, 0x43, 0x4b, 0xa4, 0xe6, 0x91, 0xb2, 0xc5, 0x3a, 0xb0, 0xd7, 0xd7, 0x92,
	0xa4, 0x20, 0x39, 0xc7, 0x40, 0xd5, 0x3d, 0xb5, 0x69, 0xe7, 0xe4, 0x40, 0x68, 0x91, 0xa2, 0x42,
	0x4d, 0x81, 0xfc, 0x1f, 0xc8, 0x0d, 0x3b, 0xef, 0x7b, 0x87, 0x1e, 0x88, 0x5b, 0x51, 0x67, 0x97,
	0x17, 0x6a, 0x6d, 0x5b, 0x6f, 0x11, 0x34, 0x38, 0xce, 0xcd, 0x33, 0xfe, 0xd1, 0xba, 0x56, 0x43,
	0x55, 0x7f, 0x1a, 0x6a, 0x5c, 0xf7, 0xef, 0xf0, 0xe2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x83,
	0x03, 0x96, 0xca, 0x02, 0x00, 0x00,
}
