// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/containers.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageContainer struct {
	AggregateRootID      string   `protobuf:"bytes,1,opt,name=AggregateRootID,proto3" json:"AggregateRootID,omitempty"`
	MessageType          string   `protobuf:"bytes,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageContainer) Reset()         { *m = MessageContainer{} }
func (m *MessageContainer) String() string { return proto.CompactTextString(m) }
func (*MessageContainer) ProtoMessage()    {}
func (*MessageContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_containers_709bf596682bd895, []int{0}
}
func (m *MessageContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContainer.Unmarshal(m, b)
}
func (m *MessageContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContainer.Marshal(b, m, deterministic)
}
func (dst *MessageContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContainer.Merge(dst, src)
}
func (m *MessageContainer) XXX_Size() int {
	return xxx_messageInfo_MessageContainer.Size(m)
}
func (m *MessageContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContainer.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContainer proto.InternalMessageInfo

func (m *MessageContainer) GetAggregateRootID() string {
	if m != nil {
		return m.AggregateRootID
	}
	return ""
}

func (m *MessageContainer) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *MessageContainer) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageContainer)(nil), "messages.MessageContainer")
}

func init() {
	proto.RegisterFile("messages/containers.proto", fileDescriptor_containers_709bf596682bd895)
}

var fileDescriptor_containers_709bf596682bd895 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcc, 0xcc, 0x4b, 0x2d, 0x2a, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x49, 0x29, 0x55, 0x70, 0x09, 0xf8, 0x42, 0xd8,
	0xce, 0x30, 0x45, 0x42, 0x1a, 0x5c, 0xfc, 0x8e, 0xe9, 0xe9, 0x45, 0xa9, 0xe9, 0x89, 0x25, 0xa9,
	0x41, 0xf9, 0xf9, 0x25, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xe8, 0xc2, 0x42,
	0x0a, 0x5c, 0xdc, 0x50, 0xdd, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x4c, 0x60, 0x55, 0xc8, 0x42, 0x42,
	0x12, 0x5c, 0xec, 0x01, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c,
	0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x29, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xc0,
	0x9f, 0xea, 0xa7, 0x00, 0x00, 0x00,
}
