// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/events.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnitCreatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitCreatedEvent) Reset()         { *m = UnitCreatedEvent{} }
func (m *UnitCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*UnitCreatedEvent) ProtoMessage()    {}
func (*UnitCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_52342d70867dc139, []int{0}
}
func (m *UnitCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitCreatedEvent.Unmarshal(m, b)
}
func (m *UnitCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *UnitCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitCreatedEvent.Merge(dst, src)
}
func (m *UnitCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_UnitCreatedEvent.Size(m)
}
func (m *UnitCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UnitCreatedEvent proto.InternalMessageInfo

func (m *UnitCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *UnitCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *UnitCreatedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitCreatedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UnitCreatedEvent) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type PrivilegeGrantedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	PollingRight         bool     `protobuf:"varint,4,opt,name=PollingRight,proto3" json:"PollingRight,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeGrantedEvent) Reset()         { *m = PrivilegeGrantedEvent{} }
func (m *PrivilegeGrantedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeGrantedEvent) ProtoMessage()    {}
func (*PrivilegeGrantedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_52342d70867dc139, []int{1}
}
func (m *PrivilegeGrantedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeGrantedEvent.Unmarshal(m, b)
}
func (m *PrivilegeGrantedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeGrantedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeGrantedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeGrantedEvent.Merge(dst, src)
}
func (m *PrivilegeGrantedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeGrantedEvent.Size(m)
}
func (m *PrivilegeGrantedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeGrantedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeGrantedEvent proto.InternalMessageInfo

func (m *PrivilegeGrantedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetPollingRight() bool {
	if m != nil {
		return m.PollingRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type PrivilegeRevokedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	Weight               uint32   `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeRevokedEvent) Reset()         { *m = PrivilegeRevokedEvent{} }
func (m *PrivilegeRevokedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeRevokedEvent) ProtoMessage()    {}
func (*PrivilegeRevokedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_52342d70867dc139, []int{2}
}
func (m *PrivilegeRevokedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeRevokedEvent.Unmarshal(m, b)
}
func (m *PrivilegeRevokedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeRevokedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeRevokedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeRevokedEvent.Merge(dst, src)
}
func (m *PrivilegeRevokedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeRevokedEvent.Size(m)
}
func (m *PrivilegeRevokedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeRevokedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeRevokedEvent proto.InternalMessageInfo

func (m *PrivilegeRevokedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*UnitCreatedEvent)(nil), "messages.UnitCreatedEvent")
	proto.RegisterType((*PrivilegeGrantedEvent)(nil), "messages.PrivilegeGrantedEvent")
	proto.RegisterType((*PrivilegeRevokedEvent)(nil), "messages.PrivilegeRevokedEvent")
}

func init() { proto.RegisterFile("messages/events.proto", fileDescriptor_events_52342d70867dc139) }

var fileDescriptor_events_52342d70867dc139 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x4e, 0xf3, 0x30,
	0x10, 0xc7, 0x95, 0x7e, 0x6d, 0xbf, 0x60, 0x40, 0x54, 0x96, 0x8a, 0x42, 0xc5, 0x50, 0x75, 0xaa,
	0x18, 0x60, 0x60, 0x63, 0x25, 0x08, 0x45, 0xa2, 0x28, 0xb2, 0x54, 0x18, 0x91, 0xdb, 0x1e, 0xc1,
	0x22, 0xb6, 0x8b, 0x7d, 0xcd, 0x03, 0xf0, 0x06, 0xac, 0xbc, 0x02, 0x6f, 0xc0, 0xd3, 0x21, 0x3b,
	0x21, 0xa4, 0x45, 0x6c, 0xb0, 0xe5, 0x7e, 0xf7, 0xb3, 0x73, 0xff, 0x93, 0x49, 0x5f, 0x82, 0xb5,
	0x3c, 0x03, 0x7b, 0x02, 0x05, 0x28, 0xb4, 0xc7, 0x4b, 0xa3, 0x51, 0xd3, 0xf0, 0x13, 0x0f, 0x0e,
	0x6b, 0x61, 0xbe, 0xb2, 0xa8, 0xe5, 0xdd, 0xbd, 0x80, 0x7c, 0x51, 0x79, 0xa3, 0xf7, 0x80, 0xf4,
	0xa6, 0x4a, 0xe0, 0xb9, 0x01, 0x8e, 0xb0, 0xb8, 0x70, 0x77, 0xd0, 0x7d, 0xd2, 0x75, 0x2c, 0x89,
	0xa3, 0x60, 0x18, 0x8c, 0xb7, 0x58, 0x55, 0xd1, 0x21, 0xd9, 0x66, 0xf0, 0xb4, 0x02, 0x8b, 0x60,
	0x92, 0x38, 0x6a, 0xf9, 0x66, 0x13, 0x51, 0x4a, 0xda, 0xd7, 0x5c, 0x42, 0xf4, 0xcf, 0xb7, 0xfc,
	0xb7, 0x3b, 0x15, 0x83, 0x9d, 0x1b, 0xb1, 0x44, 0xa1, 0x55, 0xd4, 0x2e, 0x4f, 0x35, 0x10, 0x3d,
	0x22, 0xbd, 0x29, 0xbb, 0x4a, 0xb9, 0xe1, 0x12, 0x10, 0x8c, 0xbf, 0xa1, 0xe3, 0xb5, 0x6f, 0xfc,
	0x8c, 0xbc, 0x3e, 0x1f, 0x54, 0xf3, 0x8c, 0xde, 0x5a, 0xa4, 0x9f, 0x1a, 0x51, 0x88, 0x1c, 0x32,
	0xb8, 0x34, 0x5c, 0xfd, 0x42, 0x82, 0x01, 0x09, 0x27, 0x20, 0x67, 0xbe, 0x5d, 0xa6, 0xa8, 0x6b,
	0x3a, 0x22, 0x3b, 0xa9, 0xce, 0x73, 0xa1, 0x32, 0x26, 0xb2, 0x07, 0xf4, 0x51, 0x42, 0xb6, 0xc6,
	0xdc, 0x1f, 0x6e, 0x34, 0xd6, 0x4a, 0xc7, 0x2b, 0x4d, 0x44, 0xc7, 0x64, 0x2f, 0x51, 0x02, 0x05,
	0x47, 0x51, 0x40, 0x69, 0x75, 0xbd, 0xb5, 0x89, 0x9d, 0x39, 0xe1, 0x8a, 0x67, 0x20, 0x41, 0x61,
	0x69, 0xfe, 0x2f, 0xcd, 0x0d, 0xec, 0xf2, 0xde, 0x82, 0x17, 0xc2, 0x61, 0x30, 0xde, 0x65, 0x55,
	0xb5, 0xb6, 0xad, 0x97, 0xa0, 0xb1, 0x2d, 0x06, 0x85, 0x7e, 0xfc, 0xdb, 0x6d, 0x7d, 0xcd, 0xd4,
	0xfe, 0x69, 0xa6, 0x59, 0xd7, 0xbf, 0xc2, 0xd3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xf2,
	0xa8, 0x39, 0xc6, 0x02, 0x00, 0x00,
}
