// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/github.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateGithubManagedUnit struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParemeterName     string   `protobuf:"bytes,5,opt,name=URLParemeterName,proto3" json:"URLParemeterName,omitempty"`
	VoterIDs             []string `protobuf:"bytes,6,rep,name=VoterIDs,proto3" json:"VoterIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGithubManagedUnit) Reset()         { *m = CreateGithubManagedUnit{} }
func (m *CreateGithubManagedUnit) String() string { return proto.CompactTextString(m) }
func (*CreateGithubManagedUnit) ProtoMessage()    {}
func (*CreateGithubManagedUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_github_b6fe97818a7455d8, []int{0}
}
func (m *CreateGithubManagedUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGithubManagedUnit.Unmarshal(m, b)
}
func (m *CreateGithubManagedUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGithubManagedUnit.Marshal(b, m, deterministic)
}
func (dst *CreateGithubManagedUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGithubManagedUnit.Merge(dst, src)
}
func (m *CreateGithubManagedUnit) XXX_Size() int {
	return xxx_messageInfo_CreateGithubManagedUnit.Size(m)
}
func (m *CreateGithubManagedUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGithubManagedUnit.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGithubManagedUnit proto.InternalMessageInfo

func (m *CreateGithubManagedUnit) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateGithubManagedUnit) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateGithubManagedUnit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGithubManagedUnit) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateGithubManagedUnit) GetURLParemeterName() string {
	if m != nil {
		return m.URLParemeterName
	}
	return ""
}

func (m *CreateGithubManagedUnit) GetVoterIDs() []string {
	if m != nil {
		return m.VoterIDs
	}
	return nil
}

type SyncPullRequestCmd struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	UnitID               string   `protobuf:"bytes,2,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,3,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	InitiatorID          string   `protobuf:"bytes,4,opt,name=InitiatorID,proto3" json:"InitiatorID,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CommitID             string   `protobuf:"bytes,6,opt,name=CommitID,proto3" json:"CommitID,omitempty"`
	PRID                 string   `protobuf:"bytes,7,opt,name=PRID,proto3" json:"PRID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPullRequestCmd) Reset()         { *m = SyncPullRequestCmd{} }
func (m *SyncPullRequestCmd) String() string { return proto.CompactTextString(m) }
func (*SyncPullRequestCmd) ProtoMessage()    {}
func (*SyncPullRequestCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_github_b6fe97818a7455d8, []int{1}
}
func (m *SyncPullRequestCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPullRequestCmd.Unmarshal(m, b)
}
func (m *SyncPullRequestCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPullRequestCmd.Marshal(b, m, deterministic)
}
func (dst *SyncPullRequestCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPullRequestCmd.Merge(dst, src)
}
func (m *SyncPullRequestCmd) XXX_Size() int {
	return xxx_messageInfo_SyncPullRequestCmd.Size(m)
}
func (m *SyncPullRequestCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPullRequestCmd.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPullRequestCmd proto.InternalMessageInfo

func (m *SyncPullRequestCmd) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *SyncPullRequestCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *SyncPullRequestCmd) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *SyncPullRequestCmd) GetInitiatorID() string {
	if m != nil {
		return m.InitiatorID
	}
	return ""
}

func (m *SyncPullRequestCmd) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *SyncPullRequestCmd) GetCommitID() string {
	if m != nil {
		return m.CommitID
	}
	return ""
}

func (m *SyncPullRequestCmd) GetPRID() string {
	if m != nil {
		return m.PRID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateGithubManagedUnit)(nil), "messages.CreateGithubManagedUnit")
	proto.RegisterType((*SyncPullRequestCmd)(nil), "messages.SyncPullRequestCmd")
}

func init() { proto.RegisterFile("messages/github.proto", fileDescriptor_github_b6fe97818a7455d8) }

var fileDescriptor_github_b6fe97818a7455d8 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x1c, 0xa5, 0xdb, 0xec, 0xb6, 0xcc, 0x83, 0x04, 0xd4, 0x6c, 0x78, 0x18, 0x3b, 0x0d, 0x0f, 0x7a,
	0xf0, 0xb6, 0x9b, 0xac, 0x20, 0x01, 0x95, 0x12, 0x99, 0x57, 0xc9, 0xda, 0x9f, 0x35, 0xd0, 0x34,
	0x33, 0x49, 0x05, 0xaf, 0xfb, 0x18, 0xfb, 0x6e, 0x1e, 0xfd, 0x1e, 0x92, 0xf4, 0x0f, 0x1d, 0x9e,
	0x9a, 0xf7, 0x7e, 0xef, 0x35, 0xef, 0xfd, 0x82, 0xce, 0x25, 0x18, 0xc3, 0x33, 0x30, 0xb7, 0x99,
	0xb0, 0x1f, 0xe5, 0xf6, 0x66, 0xa7, 0x95, 0x55, 0x78, 0xd4, 0xd0, 0xb3, 0xab, 0x56, 0x90, 0x94,
	0xc6, 0x2a, 0xf9, 0xf6, 0x2e, 0x20, 0x4f, 0x4d, 0xa5, 0x5b, 0xfc, 0x04, 0xe8, 0x72, 0xad, 0x81,
	0x5b, 0x78, 0xf0, 0xf6, 0x27, 0x5e, 0xf0, 0x0c, 0xd2, 0x4d, 0x21, 0x2c, 0xbe, 0x40, 0xa1, 0xfb,
	0xd2, 0x88, 0x04, 0xf3, 0x60, 0x39, 0x66, 0x35, 0xc2, 0x73, 0x34, 0x61, 0xf0, 0x59, 0x82, 0xb1,
	0xa0, 0x69, 0x44, 0x7a, 0x7e, 0xd8, 0xa5, 0x30, 0x46, 0x83, 0x67, 0x2e, 0x81, 0xf4, 0xfd, 0xc8,
	0x9f, 0x9d, 0x2b, 0x02, 0x93, 0x68, 0xb1, 0xb3, 0x42, 0x15, 0x64, 0x50, 0xb9, 0x3a, 0x14, 0xbe,
	0x46, 0x67, 0x1b, 0xf6, 0x18, 0x73, 0x0d, 0x12, 0x2c, 0x68, 0xff, 0x87, 0x13, 0x2f, 0xfb, 0xc7,
	0xe3, 0x19, 0x1a, 0xbd, 0x2a, 0x7f, 0x99, 0x21, 0xe1, 0xbc, 0xbf, 0x1c, 0xb3, 0x16, 0xaf, 0xd0,
	0x61, 0x3f, 0xad, 0xb3, 0x2e, 0x7e, 0x03, 0x84, 0x5f, 0xbe, 0x8b, 0x24, 0x2e, 0xf3, 0xbc, 0x4e,
	0xb8, 0x96, 0x29, 0x26, 0x68, 0x48, 0x8d, 0x29, 0xa1, 0xed, 0xd6, 0xc0, 0x4e, 0xe9, 0xde, 0x51,
	0xe9, 0x05, 0x3a, 0xa5, 0x85, 0xb0, 0x82, 0x5b, 0xf1, 0xe5, 0x6c, 0x55, 0xb5, 0x23, 0xce, 0x55,
	0xac, 0xb1, 0x72, 0x8b, 0xa9, 0x2b, 0x76, 0x28, 0x17, 0x9b, 0x9a, 0xfb, 0xc4, 0xe9, 0x7d, 0xb5,
	0x11, 0x6b, 0xb1, 0x9b, 0xad, 0x95, 0x94, 0xfe, 0xee, 0xd0, 0x5b, 0x5b, 0xec, 0x16, 0x1a, 0x33,
	0x1a, 0x91, 0x61, 0xb5, 0x50, 0x77, 0x5e, 0x4d, 0x0e, 0xfb, 0x69, 0x13, 0x7b, 0x1b, 0xfa, 0xe7,
	0xbc, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x35, 0x33, 0x97, 0x0f, 0x02, 0x00, 0x00,
}
