// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/issue_aggregate.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateIssueCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	IssueID              string   `protobuf:"bytes,5,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,6,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIssueCmd) Reset()         { *m = CreateIssueCmd{} }
func (m *CreateIssueCmd) String() string { return proto.CompactTextString(m) }
func (*CreateIssueCmd) ProtoMessage()    {}
func (*CreateIssueCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{0}
}
func (m *CreateIssueCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIssueCmd.Unmarshal(m, b)
}
func (m *CreateIssueCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIssueCmd.Marshal(b, m, deterministic)
}
func (dst *CreateIssueCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIssueCmd.Merge(dst, src)
}
func (m *CreateIssueCmd) XXX_Size() int {
	return xxx_messageInfo_CreateIssueCmd.Size(m)
}
func (m *CreateIssueCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIssueCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIssueCmd proto.InternalMessageInfo

func (m *CreateIssueCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateIssueCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateIssueCmd) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *CreateIssueCmd) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *CreateIssueCmd) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateIssueCmd) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateIssueCmd) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type IssueCreatedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	IssueID              string   `protobuf:"bytes,5,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,6,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueCreatedEvt) Reset()         { *m = IssueCreatedEvt{} }
func (m *IssueCreatedEvt) String() string { return proto.CompactTextString(m) }
func (*IssueCreatedEvt) ProtoMessage()    {}
func (*IssueCreatedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{1}
}
func (m *IssueCreatedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueCreatedEvt.Unmarshal(m, b)
}
func (m *IssueCreatedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueCreatedEvt.Marshal(b, m, deterministic)
}
func (dst *IssueCreatedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueCreatedEvt.Merge(dst, src)
}
func (m *IssueCreatedEvt) XXX_Size() int {
	return xxx_messageInfo_IssueCreatedEvt.Size(m)
}
func (m *IssueCreatedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueCreatedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_IssueCreatedEvt proto.InternalMessageInfo

func (m *IssueCreatedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *IssueCreatedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *IssueCreatedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *IssueCreatedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *IssueCreatedEvt) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *IssueCreatedEvt) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *IssueCreatedEvt) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateInitiativeRequestedCmd struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,3,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeRequestedCmd) Reset()         { *m = CreateInitiativeRequestedCmd{} }
func (m *CreateInitiativeRequestedCmd) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeRequestedCmd) ProtoMessage()    {}
func (*CreateInitiativeRequestedCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{2}
}
func (m *CreateInitiativeRequestedCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeRequestedCmd.Unmarshal(m, b)
}
func (m *CreateInitiativeRequestedCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeRequestedCmd.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeRequestedCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeRequestedCmd.Merge(dst, src)
}
func (m *CreateInitiativeRequestedCmd) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeRequestedCmd.Size(m)
}
func (m *CreateInitiativeRequestedCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeRequestedCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeRequestedCmd proto.InternalMessageInfo

func (m *CreateInitiativeRequestedCmd) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeRequestedCmd) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateInitiativeRequestedCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateInitiativeRequestedCmd) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type InitiativeCreatedRequestedEvt struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	UnitID               string   `protobuf:"bytes,2,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	PolicyID             string   `protobuf:"bytes,4,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,5,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,6,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedRequestedEvt) Reset()         { *m = InitiativeCreatedRequestedEvt{} }
func (m *InitiativeCreatedRequestedEvt) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedRequestedEvt) ProtoMessage()    {}
func (*InitiativeCreatedRequestedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{3}
}
func (m *InitiativeCreatedRequestedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedRequestedEvt.Unmarshal(m, b)
}
func (m *InitiativeCreatedRequestedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedRequestedEvt.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedRequestedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedRequestedEvt.Merge(dst, src)
}
func (m *InitiativeCreatedRequestedEvt) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedRequestedEvt.Size(m)
}
func (m *InitiativeCreatedRequestedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedRequestedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedRequestedEvt proto.InternalMessageInfo

func (m *InitiativeCreatedRequestedEvt) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvt) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateInitiativeRejectedCmd struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeRejectedCmd) Reset()         { *m = CreateInitiativeRejectedCmd{} }
func (m *CreateInitiativeRejectedCmd) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeRejectedCmd) ProtoMessage()    {}
func (*CreateInitiativeRejectedCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{4}
}
func (m *CreateInitiativeRejectedCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeRejectedCmd.Unmarshal(m, b)
}
func (m *CreateInitiativeRejectedCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeRejectedCmd.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeRejectedCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeRejectedCmd.Merge(dst, src)
}
func (m *CreateInitiativeRejectedCmd) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeRejectedCmd.Size(m)
}
func (m *CreateInitiativeRejectedCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeRejectedCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeRejectedCmd proto.InternalMessageInfo

func (m *CreateInitiativeRejectedCmd) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeRejectedCmd) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateInitiativeRejectedCmd) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type InitiativeCreatedRejectedEvt struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedRejectedEvt) Reset()         { *m = InitiativeCreatedRejectedEvt{} }
func (m *InitiativeCreatedRejectedEvt) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedRejectedEvt) ProtoMessage()    {}
func (*InitiativeCreatedRejectedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{5}
}
func (m *InitiativeCreatedRejectedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedRejectedEvt.Unmarshal(m, b)
}
func (m *InitiativeCreatedRejectedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedRejectedEvt.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedRejectedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedRejectedEvt.Merge(dst, src)
}
func (m *InitiativeCreatedRejectedEvt) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedRejectedEvt.Size(m)
}
func (m *InitiativeCreatedRejectedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedRejectedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedRejectedEvt proto.InternalMessageInfo

func (m *InitiativeCreatedRejectedEvt) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedRejectedEvt) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedRejectedEvt) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type CreateInitiativeAcceptedCmd struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeAcceptedCmd) Reset()         { *m = CreateInitiativeAcceptedCmd{} }
func (m *CreateInitiativeAcceptedCmd) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeAcceptedCmd) ProtoMessage()    {}
func (*CreateInitiativeAcceptedCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{6}
}
func (m *CreateInitiativeAcceptedCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeAcceptedCmd.Unmarshal(m, b)
}
func (m *CreateInitiativeAcceptedCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeAcceptedCmd.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeAcceptedCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeAcceptedCmd.Merge(dst, src)
}
func (m *CreateInitiativeAcceptedCmd) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeAcceptedCmd.Size(m)
}
func (m *CreateInitiativeAcceptedCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeAcceptedCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeAcceptedCmd proto.InternalMessageInfo

func (m *CreateInitiativeAcceptedCmd) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeAcceptedCmd) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

type InitiativeCreatedAcceptedEvt struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	UnitID               string   `protobuf:"bytes,2,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	PolicyID             string   `protobuf:"bytes,4,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,5,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,6,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedAcceptedEvt) Reset()         { *m = InitiativeCreatedAcceptedEvt{} }
func (m *InitiativeCreatedAcceptedEvt) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedAcceptedEvt) ProtoMessage()    {}
func (*InitiativeCreatedAcceptedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_04afd9f3220f405a, []int{7}
}
func (m *InitiativeCreatedAcceptedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvt.Unmarshal(m, b)
}
func (m *InitiativeCreatedAcceptedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvt.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedAcceptedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedAcceptedEvt.Merge(dst, src)
}
func (m *InitiativeCreatedAcceptedEvt) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvt.Size(m)
}
func (m *InitiativeCreatedAcceptedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedAcceptedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedAcceptedEvt proto.InternalMessageInfo

func (m *InitiativeCreatedAcceptedEvt) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvt) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateIssueCmd)(nil), "messages.CreateIssueCmd")
	proto.RegisterType((*IssueCreatedEvt)(nil), "messages.IssueCreatedEvt")
	proto.RegisterType((*CreateInitiativeRequestedCmd)(nil), "messages.CreateInitiativeRequestedCmd")
	proto.RegisterType((*InitiativeCreatedRequestedEvt)(nil), "messages.InitiativeCreatedRequestedEvt")
	proto.RegisterType((*CreateInitiativeRejectedCmd)(nil), "messages.CreateInitiativeRejectedCmd")
	proto.RegisterType((*InitiativeCreatedRejectedEvt)(nil), "messages.InitiativeCreatedRejectedEvt")
	proto.RegisterType((*CreateInitiativeAcceptedCmd)(nil), "messages.CreateInitiativeAcceptedCmd")
	proto.RegisterType((*InitiativeCreatedAcceptedEvt)(nil), "messages.InitiativeCreatedAcceptedEvt")
}

func init() {
	proto.RegisterFile("messages/issue_aggregate.proto", fileDescriptor_issue_aggregate_04afd9f3220f405a)
}

var fileDescriptor_issue_aggregate_04afd9f3220f405a = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xce, 0x40, 0x29, 0xdc, 0xc3, 0xcd, 0xbd, 0xc9, 0x2c, 0xc8, 0x5c, 0x2e, 0x1a, 0xc2, 0xca,
	0x95, 0x2e, 0xdc, 0xb9, 0x43, 0xea, 0x62, 0x76, 0x86, 0xc4, 0x35, 0x19, 0xdb, 0x63, 0x1d, 0x03,
	0x14, 0x3b, 0x03, 0x09, 0x3b, 0xf5, 0x31, 0xdc, 0xf8, 0x64, 0xfa, 0x02, 0xfa, 0x10, 0xa6, 0x53,
	0xa6, 0x50, 0xa0, 0xb8, 0x61, 0xc5, 0xae, 0x67, 0xbe, 0xe9, 0xf9, 0xfe, 0x9a, 0xc2, 0xf1, 0x08,
	0x95, 0x12, 0x21, 0xaa, 0x33, 0xa9, 0xd4, 0x14, 0x07, 0x22, 0x0c, 0x63, 0x0c, 0x85, 0xc6, 0xd3,
	0x49, 0x1c, 0xe9, 0x88, 0xd6, 0x2c, 0xde, 0x6c, 0x65, 0x37, 0xfd, 0xa9, 0xd2, 0xd1, 0x68, 0x70,
	0x27, 0x71, 0x18, 0xa8, 0xf4, 0x5e, 0xe7, 0x9d, 0xc0, 0x9f, 0x5e, 0x8c, 0x42, 0x23, 0x4f, 0xf6,
	0xf4, 0x46, 0x01, 0x6d, 0x80, 0x7b, 0x33, 0x96, 0x9a, 0x7b, 0x8c, 0xb4, 0xc9, 0xc9, 0xaf, 0xfe,
	0x62, 0xa2, 0x6d, 0xa8, 0xf7, 0xf1, 0x71, 0x8a, 0x4a, 0x63, 0xcc, 0x3d, 0x56, 0x32, 0xe0, 0xea,
	0x11, 0x6d, 0x42, 0xed, 0x3a, 0x1a, 0x4a, 0x7f, 0xce, 0x3d, 0x56, 0x36, 0x70, 0x36, 0x27, 0x5b,
	0xbb, 0x31, 0x0a, 0xee, 0x31, 0x27, 0xdd, 0x9a, 0x4e, 0x94, 0x41, 0xd5, 0x30, 0x73, 0x8f, 0x55,
	0x0c, 0x60, 0x47, 0xda, 0x81, 0xdf, 0x7c, 0x2c, 0xb5, 0x14, 0x5a, 0xce, 0x12, 0xd8, 0x35, 0x70,
	0xee, 0x8c, 0x52, 0x70, 0x2e, 0xa3, 0x60, 0xce, 0xaa, 0x06, 0x33, 0xcf, 0x17, 0xf5, 0xd7, 0x97,
	0x7f, 0x76, 0x49, 0xe7, 0x83, 0xc0, 0xdf, 0xd4, 0x99, 0x31, 0x19, 0x5c, 0xcd, 0xf4, 0x61, 0x19,
	0x7c, 0x23, 0xd0, 0x5a, 0x14, 0x98, 0xbd, 0x67, 0x25, 0x07, 0x49, 0x9d, 0x2b, 0xfc, 0x64, 0x37,
	0x7f, 0x69, 0x0b, 0xff, 0x5a, 0x26, 0xe5, 0xcd, 0x4c, 0xac, 0x42, 0xa7, 0x48, 0xe1, 0x17, 0x81,
	0xa3, 0xe5, 0xce, 0x45, 0x0f, 0x99, 0xc4, 0xa4, 0x90, 0x62, 0x89, 0xcb, 0xaa, 0x4a, 0xb9, 0xaa,
	0x96, 0x61, 0x97, 0x73, 0x61, 0xaf, 0x16, 0xe4, 0xac, 0x15, 0xb4, 0x6e, 0xb7, 0xf2, 0xb3, 0x5d,
	0xb7, 0xd8, 0x6e, 0x61, 0x21, 0x4f, 0x04, 0xfe, 0x6f, 0x16, 0xf2, 0x80, 0xfe, 0x5e, 0xfa, 0x68,
	0x80, 0xdb, 0x47, 0xa1, 0xa2, 0xb1, 0x35, 0x9e, 0x4e, 0x79, 0x09, 0xcf, 0x04, 0x5a, 0x5b, 0x12,
	0x4f, 0x35, 0xec, 0x0e, 0x7c, 0x6f, 0x1a, 0xee, 0x37, 0x53, 0xe8, 0xfa, 0x3e, 0x4e, 0xf6, 0x91,
	0x42, 0x9e, 0xe9, 0x73, 0x9b, 0x5b, 0xcb, 0x75, 0x68, 0x9f, 0xd7, 0xad, 0x6b, 0xfe, 0xdb, 0xe7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x51, 0x6f, 0x86, 0x01, 0x06, 0x00, 0x00,
}
