// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/issue_aggregate.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateIssueCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	IssueID              string   `protobuf:"bytes,5,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,6,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIssueCommand) Reset()         { *m = CreateIssueCommand{} }
func (m *CreateIssueCommand) String() string { return proto.CompactTextString(m) }
func (*CreateIssueCommand) ProtoMessage()    {}
func (*CreateIssueCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{0}
}
func (m *CreateIssueCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIssueCommand.Unmarshal(m, b)
}
func (m *CreateIssueCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIssueCommand.Marshal(b, m, deterministic)
}
func (dst *CreateIssueCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIssueCommand.Merge(dst, src)
}
func (m *CreateIssueCommand) XXX_Size() int {
	return xxx_messageInfo_CreateIssueCommand.Size(m)
}
func (m *CreateIssueCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIssueCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIssueCommand proto.InternalMessageInfo

func (m *CreateIssueCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateIssueCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateIssueCommand) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *CreateIssueCommand) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *CreateIssueCommand) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateIssueCommand) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateIssueCommand) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type IssueCreatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	IssueID              string   `protobuf:"bytes,5,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,6,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueCreatedEvent) Reset()         { *m = IssueCreatedEvent{} }
func (m *IssueCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*IssueCreatedEvent) ProtoMessage()    {}
func (*IssueCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{1}
}
func (m *IssueCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueCreatedEvent.Unmarshal(m, b)
}
func (m *IssueCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *IssueCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueCreatedEvent.Merge(dst, src)
}
func (m *IssueCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_IssueCreatedEvent.Size(m)
}
func (m *IssueCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IssueCreatedEvent proto.InternalMessageInfo

func (m *IssueCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *IssueCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *IssueCreatedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *IssueCreatedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *IssueCreatedEvent) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *IssueCreatedEvent) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *IssueCreatedEvent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateInitiativeRequestedCommand struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,3,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeRequestedCommand) Reset()         { *m = CreateInitiativeRequestedCommand{} }
func (m *CreateInitiativeRequestedCommand) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeRequestedCommand) ProtoMessage()    {}
func (*CreateInitiativeRequestedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{2}
}
func (m *CreateInitiativeRequestedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeRequestedCommand.Unmarshal(m, b)
}
func (m *CreateInitiativeRequestedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeRequestedCommand.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeRequestedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeRequestedCommand.Merge(dst, src)
}
func (m *CreateInitiativeRequestedCommand) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeRequestedCommand.Size(m)
}
func (m *CreateInitiativeRequestedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeRequestedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeRequestedCommand proto.InternalMessageInfo

func (m *CreateInitiativeRequestedCommand) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeRequestedCommand) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateInitiativeRequestedCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateInitiativeRequestedCommand) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type InitiativeCreatedRequestedEvent struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	UnitID               string   `protobuf:"bytes,2,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	PolicyID             string   `protobuf:"bytes,4,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,5,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,6,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedRequestedEvent) Reset()         { *m = InitiativeCreatedRequestedEvent{} }
func (m *InitiativeCreatedRequestedEvent) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedRequestedEvent) ProtoMessage()    {}
func (*InitiativeCreatedRequestedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{3}
}
func (m *InitiativeCreatedRequestedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedRequestedEvent.Unmarshal(m, b)
}
func (m *InitiativeCreatedRequestedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedRequestedEvent.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedRequestedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedRequestedEvent.Merge(dst, src)
}
func (m *InitiativeCreatedRequestedEvent) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedRequestedEvent.Size(m)
}
func (m *InitiativeCreatedRequestedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedRequestedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedRequestedEvent proto.InternalMessageInfo

func (m *InitiativeCreatedRequestedEvent) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *InitiativeCreatedRequestedEvent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateInitiativeRejectedCommand struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeRejectedCommand) Reset()         { *m = CreateInitiativeRejectedCommand{} }
func (m *CreateInitiativeRejectedCommand) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeRejectedCommand) ProtoMessage()    {}
func (*CreateInitiativeRejectedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{4}
}
func (m *CreateInitiativeRejectedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeRejectedCommand.Unmarshal(m, b)
}
func (m *CreateInitiativeRejectedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeRejectedCommand.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeRejectedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeRejectedCommand.Merge(dst, src)
}
func (m *CreateInitiativeRejectedCommand) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeRejectedCommand.Size(m)
}
func (m *CreateInitiativeRejectedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeRejectedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeRejectedCommand proto.InternalMessageInfo

func (m *CreateInitiativeRejectedCommand) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeRejectedCommand) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *CreateInitiativeRejectedCommand) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type InitiativeCreatedRejectedEvent struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedRejectedEvent) Reset()         { *m = InitiativeCreatedRejectedEvent{} }
func (m *InitiativeCreatedRejectedEvent) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedRejectedEvent) ProtoMessage()    {}
func (*InitiativeCreatedRejectedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{5}
}
func (m *InitiativeCreatedRejectedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedRejectedEvent.Unmarshal(m, b)
}
func (m *InitiativeCreatedRejectedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedRejectedEvent.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedRejectedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedRejectedEvent.Merge(dst, src)
}
func (m *InitiativeCreatedRejectedEvent) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedRejectedEvent.Size(m)
}
func (m *InitiativeCreatedRejectedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedRejectedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedRejectedEvent proto.InternalMessageInfo

func (m *InitiativeCreatedRejectedEvent) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedRejectedEvent) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedRejectedEvent) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type CreateInitiativeAcceptedCommand struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,2,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInitiativeAcceptedCommand) Reset()         { *m = CreateInitiativeAcceptedCommand{} }
func (m *CreateInitiativeAcceptedCommand) String() string { return proto.CompactTextString(m) }
func (*CreateInitiativeAcceptedCommand) ProtoMessage()    {}
func (*CreateInitiativeAcceptedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{6}
}
func (m *CreateInitiativeAcceptedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInitiativeAcceptedCommand.Unmarshal(m, b)
}
func (m *CreateInitiativeAcceptedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInitiativeAcceptedCommand.Marshal(b, m, deterministic)
}
func (dst *CreateInitiativeAcceptedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInitiativeAcceptedCommand.Merge(dst, src)
}
func (m *CreateInitiativeAcceptedCommand) XXX_Size() int {
	return xxx_messageInfo_CreateInitiativeAcceptedCommand.Size(m)
}
func (m *CreateInitiativeAcceptedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInitiativeAcceptedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInitiativeAcceptedCommand proto.InternalMessageInfo

func (m *CreateInitiativeAcceptedCommand) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *CreateInitiativeAcceptedCommand) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

type InitiativeCreatedAcceptedEvent struct {
	IssueID              string   `protobuf:"bytes,1,opt,name=IssueID,proto3" json:"IssueID,omitempty"`
	UnitID               string   `protobuf:"bytes,2,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	PolicyID             string   `protobuf:"bytes,4,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	InitiativeID         string   `protobuf:"bytes,5,opt,name=InitiativeID,proto3" json:"InitiativeID,omitempty"`
	RequesterID          string   `protobuf:"bytes,6,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiativeCreatedAcceptedEvent) Reset()         { *m = InitiativeCreatedAcceptedEvent{} }
func (m *InitiativeCreatedAcceptedEvent) String() string { return proto.CompactTextString(m) }
func (*InitiativeCreatedAcceptedEvent) ProtoMessage()    {}
func (*InitiativeCreatedAcceptedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_issue_aggregate_d77d02983cfa434a, []int{7}
}
func (m *InitiativeCreatedAcceptedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvent.Unmarshal(m, b)
}
func (m *InitiativeCreatedAcceptedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvent.Marshal(b, m, deterministic)
}
func (dst *InitiativeCreatedAcceptedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiativeCreatedAcceptedEvent.Merge(dst, src)
}
func (m *InitiativeCreatedAcceptedEvent) XXX_Size() int {
	return xxx_messageInfo_InitiativeCreatedAcceptedEvent.Size(m)
}
func (m *InitiativeCreatedAcceptedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiativeCreatedAcceptedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InitiativeCreatedAcceptedEvent proto.InternalMessageInfo

func (m *InitiativeCreatedAcceptedEvent) GetIssueID() string {
	if m != nil {
		return m.IssueID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetInitiativeID() string {
	if m != nil {
		return m.InitiativeID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *InitiativeCreatedAcceptedEvent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateIssueCommand)(nil), "messages.CreateIssueCommand")
	proto.RegisterType((*IssueCreatedEvent)(nil), "messages.IssueCreatedEvent")
	proto.RegisterType((*CreateInitiativeRequestedCommand)(nil), "messages.CreateInitiativeRequestedCommand")
	proto.RegisterType((*InitiativeCreatedRequestedEvent)(nil), "messages.InitiativeCreatedRequestedEvent")
	proto.RegisterType((*CreateInitiativeRejectedCommand)(nil), "messages.CreateInitiativeRejectedCommand")
	proto.RegisterType((*InitiativeCreatedRejectedEvent)(nil), "messages.InitiativeCreatedRejectedEvent")
	proto.RegisterType((*CreateInitiativeAcceptedCommand)(nil), "messages.CreateInitiativeAcceptedCommand")
	proto.RegisterType((*InitiativeCreatedAcceptedEvent)(nil), "messages.InitiativeCreatedAcceptedEvent")
}

func init() {
	proto.RegisterFile("messages/issue_aggregate.proto", fileDescriptor_issue_aggregate_d77d02983cfa434a)
}

var fileDescriptor_issue_aggregate_d77d02983cfa434a = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xbd, 0x6e, 0xea, 0x30,
	0x14, 0x96, 0x21, 0x04, 0xee, 0xe1, 0x2e, 0xd7, 0x03, 0xca, 0x45, 0x57, 0x80, 0x98, 0xee, 0xd4,
	0x0e, 0xdd, 0xba, 0x51, 0xd2, 0x21, 0x5b, 0x85, 0xd4, 0x19, 0xb9, 0xc9, 0x69, 0xe4, 0x8a, 0xc4,
	0x34, 0x36, 0x48, 0xac, 0x6d, 0x9f, 0xa2, 0x6b, 0x5f, 0xac, 0x7d, 0x80, 0xf6, 0x19, 0x2a, 0x6c,
	0x1c, 0x08, 0x90, 0xb2, 0x30, 0xb1, 0xe5, 0xf8, 0x73, 0xbe, 0xf3, 0xfd, 0x44, 0x81, 0x4e, 0x82,
	0x52, 0xb2, 0x18, 0xe5, 0x39, 0x97, 0x72, 0x86, 0x63, 0x16, 0xc7, 0x19, 0xc6, 0x4c, 0xe1, 0xd9,
	0x34, 0x13, 0x4a, 0xd0, 0x86, 0xc5, 0xdb, 0xff, 0xf2, 0x9b, 0xe1, 0x4c, 0x2a, 0x91, 0x8c, 0xef,
	0x39, 0x4e, 0x22, 0x69, 0xee, 0xf5, 0x3f, 0x08, 0xd0, 0x61, 0x86, 0x4c, 0x61, 0xb0, 0xe4, 0x19,
	0x8a, 0x24, 0x61, 0x69, 0x44, 0x5b, 0xe0, 0xde, 0xa6, 0x5c, 0x05, 0xbe, 0x47, 0x7a, 0xe4, 0xff,
	0xaf, 0xd1, 0x6a, 0xa2, 0x3d, 0x68, 0x8e, 0xf0, 0x71, 0x86, 0x52, 0x61, 0x16, 0xf8, 0x5e, 0x45,
	0x83, 0x9b, 0x47, 0xb4, 0x0d, 0x8d, 0x1b, 0x31, 0xe1, 0xe1, 0x22, 0xf0, 0xbd, 0xaa, 0x86, 0xf3,
	0x79, 0xc9, 0x3a, 0xc8, 0x90, 0x05, 0xbe, 0xe7, 0x18, 0x56, 0x33, 0x51, 0x0f, 0xea, 0x7a, 0x7b,
	0xe0, 0x7b, 0x35, 0x0d, 0xd8, 0x91, 0xf6, 0xe1, 0x77, 0x90, 0x72, 0xc5, 0x99, 0xe2, 0xf3, 0x25,
	0xec, 0x6a, 0xb8, 0x70, 0x46, 0x29, 0x38, 0x57, 0x22, 0x5a, 0x78, 0x75, 0x8d, 0xe9, 0xe7, 0xcb,
	0xe6, 0xeb, 0xd3, 0x5f, 0x4b, 0xd2, 0x7f, 0x27, 0xf0, 0xc7, 0xb8, 0xd3, 0x46, 0xa3, 0xeb, 0x39,
	0xa6, 0xea, 0xb4, 0x2c, 0xbe, 0x11, 0xe8, 0xad, 0x6a, 0xcc, 0xdf, 0xb3, 0x92, 0x23, 0x5b, 0xea,
	0x86, 0x06, 0xf2, 0xb3, 0x86, 0xca, 0x1e, 0x0d, 0x5b, 0xb9, 0x54, 0x77, 0x73, 0xb1, 0x2a, 0x9d,
	0x32, 0x95, 0x5f, 0x04, 0xba, 0x6b, 0xce, 0x55, 0x1b, 0xb9, 0x4c, 0x53, 0x4b, 0xb9, 0xc8, 0x75,
	0x61, 0x95, 0x42, 0x61, 0xeb, 0xc8, 0xab, 0x85, 0xc8, 0x37, 0x6b, 0x72, 0xb6, 0x6a, 0xda, 0x36,
	0x5c, 0x3b, 0x6c, 0xd8, 0x2d, 0x37, 0x5c, 0x5a, 0xcb, 0x0b, 0x81, 0xee, 0x6e, 0x2d, 0x0f, 0x18,
	0x1e, 0xad, 0x95, 0x16, 0xb8, 0x23, 0x64, 0x52, 0xa4, 0xd6, 0xbc, 0x99, 0x8a, 0x32, 0x9e, 0x09,
	0x74, 0xf6, 0xe4, 0x6e, 0x74, 0x1c, 0x8a, 0xfd, 0x68, 0x2a, 0x26, 0xbb, 0x59, 0x0c, 0xc2, 0x10,
	0xa7, 0xc7, 0xca, 0xa2, 0xb8, 0xed, 0x73, 0x9f, 0x67, 0xbb, 0xef, 0xf4, 0x3e, 0xb5, 0x3b, 0x57,
	0xff, 0xcf, 0x2f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x20, 0x99, 0xbf, 0x19, 0x06, 0x00,
	0x00,
}
