// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/unit_aggregate.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUnitCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitCommand) Reset()         { *m = CreateUnitCommand{} }
func (m *CreateUnitCommand) String() string { return proto.CompactTextString(m) }
func (*CreateUnitCommand) ProtoMessage()    {}
func (*CreateUnitCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{0}
}
func (m *CreateUnitCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitCommand.Unmarshal(m, b)
}
func (m *CreateUnitCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitCommand.Marshal(b, m, deterministic)
}
func (dst *CreateUnitCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitCommand.Merge(dst, src)
}
func (m *CreateUnitCommand) XXX_Size() int {
	return xxx_messageInfo_CreateUnitCommand.Size(m)
}
func (m *CreateUnitCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitCommand proto.InternalMessageInfo

func (m *CreateUnitCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateUnitCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateUnitCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUnitCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUnitCommand) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type UnitCreatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitCreatedEvent) Reset()         { *m = UnitCreatedEvent{} }
func (m *UnitCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*UnitCreatedEvent) ProtoMessage()    {}
func (*UnitCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{1}
}
func (m *UnitCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitCreatedEvent.Unmarshal(m, b)
}
func (m *UnitCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *UnitCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitCreatedEvent.Merge(dst, src)
}
func (m *UnitCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_UnitCreatedEvent.Size(m)
}
func (m *UnitCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UnitCreatedEvent proto.InternalMessageInfo

func (m *UnitCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *UnitCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *UnitCreatedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitCreatedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UnitCreatedEvent) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type GrantPrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPrivilegeCommand) Reset()         { *m = GrantPrivilegeCommand{} }
func (m *GrantPrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*GrantPrivilegeCommand) ProtoMessage()    {}
func (*GrantPrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{2}
}
func (m *GrantPrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPrivilegeCommand.Unmarshal(m, b)
}
func (m *GrantPrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *GrantPrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPrivilegeCommand.Merge(dst, src)
}
func (m *GrantPrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_GrantPrivilegeCommand.Size(m)
}
func (m *GrantPrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPrivilegeCommand proto.InternalMessageInfo

func (m *GrantPrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type PrivilegeGrantedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeGrantedEvent) Reset()         { *m = PrivilegeGrantedEvent{} }
func (m *PrivilegeGrantedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeGrantedEvent) ProtoMessage()    {}
func (*PrivilegeGrantedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{3}
}
func (m *PrivilegeGrantedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeGrantedEvent.Unmarshal(m, b)
}
func (m *PrivilegeGrantedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeGrantedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeGrantedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeGrantedEvent.Merge(dst, src)
}
func (m *PrivilegeGrantedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeGrantedEvent.Size(m)
}
func (m *PrivilegeGrantedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeGrantedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeGrantedEvent proto.InternalMessageInfo

func (m *PrivilegeGrantedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type RevokePrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePrivilegeCommand) Reset()         { *m = RevokePrivilegeCommand{} }
func (m *RevokePrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*RevokePrivilegeCommand) ProtoMessage()    {}
func (*RevokePrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{4}
}
func (m *RevokePrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePrivilegeCommand.Unmarshal(m, b)
}
func (m *RevokePrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *RevokePrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePrivilegeCommand.Merge(dst, src)
}
func (m *RevokePrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_RevokePrivilegeCommand.Size(m)
}
func (m *RevokePrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePrivilegeCommand proto.InternalMessageInfo

func (m *RevokePrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type PrivilegeRevokedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	Weight               uint32   `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeRevokedEvent) Reset()         { *m = PrivilegeRevokedEvent{} }
func (m *PrivilegeRevokedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeRevokedEvent) ProtoMessage()    {}
func (*PrivilegeRevokedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_0e9820b91a39a36b, []int{5}
}
func (m *PrivilegeRevokedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeRevokedEvent.Unmarshal(m, b)
}
func (m *PrivilegeRevokedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeRevokedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeRevokedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeRevokedEvent.Merge(dst, src)
}
func (m *PrivilegeRevokedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeRevokedEvent.Size(m)
}
func (m *PrivilegeRevokedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeRevokedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeRevokedEvent proto.InternalMessageInfo

func (m *PrivilegeRevokedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateUnitCommand)(nil), "messages.CreateUnitCommand")
	proto.RegisterType((*UnitCreatedEvent)(nil), "messages.UnitCreatedEvent")
	proto.RegisterType((*GrantPrivilegeCommand)(nil), "messages.GrantPrivilegeCommand")
	proto.RegisterType((*PrivilegeGrantedEvent)(nil), "messages.PrivilegeGrantedEvent")
	proto.RegisterType((*RevokePrivilegeCommand)(nil), "messages.RevokePrivilegeCommand")
	proto.RegisterType((*PrivilegeRevokedEvent)(nil), "messages.PrivilegeRevokedEvent")
}

func init() {
	proto.RegisterFile("messages/unit_aggregate.proto", fileDescriptor_unit_aggregate_0e9820b91a39a36b)
}

var fileDescriptor_unit_aggregate_0e9820b91a39a36b = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0x31, 0x4f, 0x3a, 0x41,
	0x10, 0xc5, 0x73, 0xfc, 0xf9, 0xe3, 0xb9, 0xc6, 0x88, 0x9b, 0x48, 0x4e, 0xa2, 0x09, 0xa1, 0x22,
	0x16, 0x5a, 0xd8, 0xd9, 0x82, 0x31, 0x24, 0x62, 0xc8, 0x26, 0x68, 0x49, 0x16, 0x18, 0xd7, 0x8d,
	0xec, 0x2e, 0xee, 0x0e, 0x57, 0x58, 0xda, 0x58, 0xdb, 0xfa, 0x51, 0xf4, 0xcb, 0x99, 0xdb, 0x45,
	0x3c, 0x21, 0x56, 0x44, 0x13, 0x3a, 0xe6, 0xcd, 0x6f, 0xb8, 0x37, 0x6f, 0x2e, 0x47, 0x0e, 0x15,
	0x38, 0xc7, 0x05, 0xb8, 0x93, 0xa9, 0x96, 0xd8, 0xe7, 0x42, 0x58, 0x10, 0x1c, 0xe1, 0x78, 0x62,
	0x0d, 0x1a, 0x1a, 0x7f, 0xb6, 0xab, 0x07, 0x73, 0x70, 0x38, 0x75, 0x68, 0x54, 0xff, 0x56, 0xc2,
	0x78, 0xe4, 0x02, 0x57, 0x7f, 0x8f, 0xc8, 0x6e, 0xd3, 0x02, 0x47, 0xe8, 0x69, 0x89, 0x4d, 0xa3,
	0x14, 0xd7, 0x23, 0x5a, 0x21, 0xa5, 0xac, 0x6c, 0xb7, 0x92, 0xa8, 0x16, 0x35, 0x36, 0xd9, 0xac,
	0xa2, 0x35, 0xb2, 0xc5, 0xe0, 0x61, 0x0a, 0x0e, 0xc1, 0xb6, 0x5b, 0x49, 0xc1, 0x37, 0xf3, 0x12,
	0xa5, 0xa4, 0x78, 0xc5, 0x15, 0x24, 0xff, 0x7c, 0xcb, 0xff, 0xce, 0xa6, 0x5a, 0xe0, 0x86, 0x56,
	0x4e, 0x50, 0x1a, 0x9d, 0x14, 0xc3, 0x54, 0x4e, 0xa2, 0x47, 0xa4, 0xdc, 0x63, 0x97, 0x5d, 0x6e,
	0xb9, 0x02, 0x04, 0xeb, 0xff, 0xe1, 0xbf, 0xc7, 0x96, 0xf4, 0x33, 0xf2, 0xfa, 0xb4, 0x3f, 0xf3,
	0x53, 0x7f, 0x8b, 0x48, 0xd9, 0xfb, 0xf6, 0x1b, 0x8c, 0xce, 0x53, 0xd0, 0xb8, 0x36, 0xe6, 0x9f,
	0x0b, 0x64, 0xef, 0xc2, 0x72, 0x8d, 0x5d, 0x2b, 0x53, 0x39, 0x06, 0x01, 0xab, 0xc7, 0x5f, 0x25,
	0x71, 0x07, 0xd4, 0xc0, 0xb7, 0xc3, 0x16, 0xf3, 0x3a, 0x9b, 0xbe, 0x36, 0x28, 0xb5, 0x60, 0x52,
	0xdc, 0xa1, 0xb7, 0x18, 0xb3, 0xbc, 0x44, 0x1b, 0x64, 0xa7, 0xad, 0x25, 0x4a, 0x8e, 0x32, 0x85,
	0x40, 0x95, 0x3c, 0xb5, 0x28, 0x67, 0x64, 0x87, 0x6b, 0x2e, 0x40, 0x81, 0xc6, 0x40, 0x6e, 0x04,
	0x72, 0x41, 0xce, 0x76, 0xb9, 0x01, 0x0f, 0xc4, 0xb5, 0xa8, 0xb1, 0xcd, 0x66, 0xd5, 0x52, 0x12,
	0xf3, 0x10, 0x7c, 0x24, 0xab, 0xdf, 0x72, 0x3d, 0x93, 0x78, 0x24, 0x15, 0x06, 0xa9, 0xb9, 0x87,
	0xbf, 0x79, 0x27, 0xbe, 0x3d, 0xfb, 0x25, 0xca, 0x5d, 0x21, 0xb8, 0xf8, 0xd5, 0x2b, 0x7c, 0xe5,
	0x51, 0xfc, 0x29, 0x8f, 0x41, 0xc9, 0x7f, 0xa5, 0x4e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0x96, 0x31, 0xca, 0xee, 0x04, 0x00, 0x00,
}
