// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/unit_aggregate.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUnitCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitCommand) Reset()         { *m = CreateUnitCommand{} }
func (m *CreateUnitCommand) String() string { return proto.CompactTextString(m) }
func (*CreateUnitCommand) ProtoMessage()    {}
func (*CreateUnitCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{0}
}
func (m *CreateUnitCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitCommand.Unmarshal(m, b)
}
func (m *CreateUnitCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitCommand.Marshal(b, m, deterministic)
}
func (dst *CreateUnitCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitCommand.Merge(dst, src)
}
func (m *CreateUnitCommand) XXX_Size() int {
	return xxx_messageInfo_CreateUnitCommand.Size(m)
}
func (m *CreateUnitCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitCommand proto.InternalMessageInfo

func (m *CreateUnitCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateUnitCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateUnitCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUnitCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUnitCommand) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type UnitCreatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitCreatedEvent) Reset()         { *m = UnitCreatedEvent{} }
func (m *UnitCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*UnitCreatedEvent) ProtoMessage()    {}
func (*UnitCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{1}
}
func (m *UnitCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitCreatedEvent.Unmarshal(m, b)
}
func (m *UnitCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *UnitCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitCreatedEvent.Merge(dst, src)
}
func (m *UnitCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_UnitCreatedEvent.Size(m)
}
func (m *UnitCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UnitCreatedEvent proto.InternalMessageInfo

func (m *UnitCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *UnitCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *UnitCreatedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitCreatedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UnitCreatedEvent) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type GrantPrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPrivilegeCommand) Reset()         { *m = GrantPrivilegeCommand{} }
func (m *GrantPrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*GrantPrivilegeCommand) ProtoMessage()    {}
func (*GrantPrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{2}
}
func (m *GrantPrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPrivilegeCommand.Unmarshal(m, b)
}
func (m *GrantPrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *GrantPrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPrivilegeCommand.Merge(dst, src)
}
func (m *GrantPrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_GrantPrivilegeCommand.Size(m)
}
func (m *GrantPrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPrivilegeCommand proto.InternalMessageInfo

func (m *GrantPrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *GrantPrivilegeCommand) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *GrantPrivilegeCommand) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type PrivilegeGrantedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeGrantedEvent) Reset()         { *m = PrivilegeGrantedEvent{} }
func (m *PrivilegeGrantedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeGrantedEvent) ProtoMessage()    {}
func (*PrivilegeGrantedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{3}
}
func (m *PrivilegeGrantedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeGrantedEvent.Unmarshal(m, b)
}
func (m *PrivilegeGrantedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeGrantedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeGrantedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeGrantedEvent.Merge(dst, src)
}
func (m *PrivilegeGrantedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeGrantedEvent.Size(m)
}
func (m *PrivilegeGrantedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeGrantedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeGrantedEvent proto.InternalMessageInfo

func (m *PrivilegeGrantedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeGrantedEvent) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *PrivilegeGrantedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type RevokePrivilegeCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePrivilegeCommand) Reset()         { *m = RevokePrivilegeCommand{} }
func (m *RevokePrivilegeCommand) String() string { return proto.CompactTextString(m) }
func (*RevokePrivilegeCommand) ProtoMessage()    {}
func (*RevokePrivilegeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{4}
}
func (m *RevokePrivilegeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePrivilegeCommand.Unmarshal(m, b)
}
func (m *RevokePrivilegeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePrivilegeCommand.Marshal(b, m, deterministic)
}
func (dst *RevokePrivilegeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePrivilegeCommand.Merge(dst, src)
}
func (m *RevokePrivilegeCommand) XXX_Size() int {
	return xxx_messageInfo_RevokePrivilegeCommand.Size(m)
}
func (m *RevokePrivilegeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePrivilegeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePrivilegeCommand proto.InternalMessageInfo

func (m *RevokePrivilegeCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *RevokePrivilegeCommand) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type PrivilegeRevokedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	Weight               uint32   `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeRevokedEvent) Reset()         { *m = PrivilegeRevokedEvent{} }
func (m *PrivilegeRevokedEvent) String() string { return proto.CompactTextString(m) }
func (*PrivilegeRevokedEvent) ProtoMessage()    {}
func (*PrivilegeRevokedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{5}
}
func (m *PrivilegeRevokedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeRevokedEvent.Unmarshal(m, b)
}
func (m *PrivilegeRevokedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeRevokedEvent.Marshal(b, m, deterministic)
}
func (dst *PrivilegeRevokedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeRevokedEvent.Merge(dst, src)
}
func (m *PrivilegeRevokedEvent) XXX_Size() int {
	return xxx_messageInfo_PrivilegeRevokedEvent.Size(m)
}
func (m *PrivilegeRevokedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeRevokedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeRevokedEvent proto.InternalMessageInfo

func (m *PrivilegeRevokedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeRevokedEvent) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type CreateAreaCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAreaCommand) Reset()         { *m = CreateAreaCommand{} }
func (m *CreateAreaCommand) String() string { return proto.CompactTextString(m) }
func (*CreateAreaCommand) ProtoMessage()    {}
func (*CreateAreaCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{6}
}
func (m *CreateAreaCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAreaCommand.Unmarshal(m, b)
}
func (m *CreateAreaCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAreaCommand.Marshal(b, m, deterministic)
}
func (dst *CreateAreaCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAreaCommand.Merge(dst, src)
}
func (m *CreateAreaCommand) XXX_Size() int {
	return xxx_messageInfo_CreateAreaCommand.Size(m)
}
func (m *CreateAreaCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAreaCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAreaCommand proto.InternalMessageInfo

func (m *CreateAreaCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateAreaCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateAreaCommand) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *CreateAreaCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAreaCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AreaCreatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaCreatedEvent) Reset()         { *m = AreaCreatedEvent{} }
func (m *AreaCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*AreaCreatedEvent) ProtoMessage()    {}
func (*AreaCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{7}
}
func (m *AreaCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaCreatedEvent.Unmarshal(m, b)
}
func (m *AreaCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *AreaCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaCreatedEvent.Merge(dst, src)
}
func (m *AreaCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_AreaCreatedEvent.Size(m)
}
func (m *AreaCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AreaCreatedEvent proto.InternalMessageInfo

func (m *AreaCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaCreatedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *AreaCreatedEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaCreatedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreatePolicyCommand struct {
	UnitID      string `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID string `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID    string `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	// Max / min amount of time before an issue is passed the Admision phase
	MinAdmissionDuration int32 `protobuf:"varint,5,opt,name=MinAdmissionDuration,proto3" json:"MinAdmissionDuration,omitempty"`
	MaxAdmissionDuration int32 `protobuf:"varint,6,opt,name=MaxAdmissionDuration,proto3" json:"MaxAdmissionDuration,omitempty"`
	// phase durations
	DiscussionDuration   int32 `protobuf:"varint,7,opt,name=DiscussionDuration,proto3" json:"DiscussionDuration,omitempty"`
	VerificationDuration int32 `protobuf:"varint,8,opt,name=VerificationDuration,proto3" json:"VerificationDuration,omitempty"`
	VotingDuration       int32 `protobuf:"varint,9,opt,name=VotingDuration,proto3" json:"VotingDuration,omitempty"`
	// quorums required (numerator / denominator)
	IssueQuorumNum       int32    `protobuf:"varint,10,opt,name=IssueQuorumNum,proto3" json:"IssueQuorumNum,omitempty"`
	IssueQuorumDen       int32    `protobuf:"varint,11,opt,name=IssueQuorumDen,proto3" json:"IssueQuorumDen,omitempty"`
	InitiativeQuorumNum  int32    `protobuf:"varint,12,opt,name=InitiativeQuorumNum,proto3" json:"InitiativeQuorumNum,omitempty"`
	InitiativeQuorumDen  int32    `protobuf:"varint,13,opt,name=InitiativeQuorumDen,proto3" json:"InitiativeQuorumDen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyCommand) Reset()         { *m = CreatePolicyCommand{} }
func (m *CreatePolicyCommand) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyCommand) ProtoMessage()    {}
func (*CreatePolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{8}
}
func (m *CreatePolicyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyCommand.Unmarshal(m, b)
}
func (m *CreatePolicyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyCommand.Marshal(b, m, deterministic)
}
func (dst *CreatePolicyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyCommand.Merge(dst, src)
}
func (m *CreatePolicyCommand) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyCommand.Size(m)
}
func (m *CreatePolicyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyCommand proto.InternalMessageInfo

func (m *CreatePolicyCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreatePolicyCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreatePolicyCommand) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *CreatePolicyCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePolicyCommand) GetMinAdmissionDuration() int32 {
	if m != nil {
		return m.MinAdmissionDuration
	}
	return 0
}

func (m *CreatePolicyCommand) GetMaxAdmissionDuration() int32 {
	if m != nil {
		return m.MaxAdmissionDuration
	}
	return 0
}

func (m *CreatePolicyCommand) GetDiscussionDuration() int32 {
	if m != nil {
		return m.DiscussionDuration
	}
	return 0
}

func (m *CreatePolicyCommand) GetVerificationDuration() int32 {
	if m != nil {
		return m.VerificationDuration
	}
	return 0
}

func (m *CreatePolicyCommand) GetVotingDuration() int32 {
	if m != nil {
		return m.VotingDuration
	}
	return 0
}

func (m *CreatePolicyCommand) GetIssueQuorumNum() int32 {
	if m != nil {
		return m.IssueQuorumNum
	}
	return 0
}

func (m *CreatePolicyCommand) GetIssueQuorumDen() int32 {
	if m != nil {
		return m.IssueQuorumDen
	}
	return 0
}

func (m *CreatePolicyCommand) GetInitiativeQuorumNum() int32 {
	if m != nil {
		return m.InitiativeQuorumNum
	}
	return 0
}

func (m *CreatePolicyCommand) GetInitiativeQuorumDen() int32 {
	if m != nil {
		return m.InitiativeQuorumDen
	}
	return 0
}

type PolicyCreatedEvent struct {
	UnitID      string `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID string `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID    string `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	// Max / min amount of time before an issue is passed the Admision phase
	MinAdmissionDuration int32 `protobuf:"varint,5,opt,name=MinAdmissionDuration,proto3" json:"MinAdmissionDuration,omitempty"`
	MaxAdmissionDuration int32 `protobuf:"varint,6,opt,name=MaxAdmissionDuration,proto3" json:"MaxAdmissionDuration,omitempty"`
	// phase durations
	DiscussionDuration   int32 `protobuf:"varint,7,opt,name=DiscussionDuration,proto3" json:"DiscussionDuration,omitempty"`
	VerificationDuration int32 `protobuf:"varint,8,opt,name=VerificationDuration,proto3" json:"VerificationDuration,omitempty"`
	VotingDuration       int32 `protobuf:"varint,9,opt,name=VotingDuration,proto3" json:"VotingDuration,omitempty"`
	// quorums required (numerator / denominator)
	IssueQuorumNum       int32    `protobuf:"varint,10,opt,name=IssueQuorumNum,proto3" json:"IssueQuorumNum,omitempty"`
	IssueQuorumDen       int32    `protobuf:"varint,11,opt,name=IssueQuorumDen,proto3" json:"IssueQuorumDen,omitempty"`
	InitiativeQuorumNum  int32    `protobuf:"varint,12,opt,name=InitiativeQuorumNum,proto3" json:"InitiativeQuorumNum,omitempty"`
	InitiativeQuorumDen  int32    `protobuf:"varint,13,opt,name=InitiativeQuorumDen,proto3" json:"InitiativeQuorumDen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyCreatedEvent) Reset()         { *m = PolicyCreatedEvent{} }
func (m *PolicyCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*PolicyCreatedEvent) ProtoMessage()    {}
func (*PolicyCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{9}
}
func (m *PolicyCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyCreatedEvent.Unmarshal(m, b)
}
func (m *PolicyCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *PolicyCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyCreatedEvent.Merge(dst, src)
}
func (m *PolicyCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_PolicyCreatedEvent.Size(m)
}
func (m *PolicyCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyCreatedEvent proto.InternalMessageInfo

func (m *PolicyCreatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PolicyCreatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PolicyCreatedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *PolicyCreatedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PolicyCreatedEvent) GetMinAdmissionDuration() int32 {
	if m != nil {
		return m.MinAdmissionDuration
	}
	return 0
}

func (m *PolicyCreatedEvent) GetMaxAdmissionDuration() int32 {
	if m != nil {
		return m.MaxAdmissionDuration
	}
	return 0
}

func (m *PolicyCreatedEvent) GetDiscussionDuration() int32 {
	if m != nil {
		return m.DiscussionDuration
	}
	return 0
}

func (m *PolicyCreatedEvent) GetVerificationDuration() int32 {
	if m != nil {
		return m.VerificationDuration
	}
	return 0
}

func (m *PolicyCreatedEvent) GetVotingDuration() int32 {
	if m != nil {
		return m.VotingDuration
	}
	return 0
}

func (m *PolicyCreatedEvent) GetIssueQuorumNum() int32 {
	if m != nil {
		return m.IssueQuorumNum
	}
	return 0
}

func (m *PolicyCreatedEvent) GetIssueQuorumDen() int32 {
	if m != nil {
		return m.IssueQuorumDen
	}
	return 0
}

func (m *PolicyCreatedEvent) GetInitiativeQuorumNum() int32 {
	if m != nil {
		return m.InitiativeQuorumNum
	}
	return 0
}

func (m *PolicyCreatedEvent) GetInitiativeQuorumDen() int32 {
	if m != nil {
		return m.InitiativeQuorumDen
	}
	return 0
}

type DeactivatePolicyCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivatePolicyCommand) Reset()         { *m = DeactivatePolicyCommand{} }
func (m *DeactivatePolicyCommand) String() string { return proto.CompactTextString(m) }
func (*DeactivatePolicyCommand) ProtoMessage()    {}
func (*DeactivatePolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{10}
}
func (m *DeactivatePolicyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivatePolicyCommand.Unmarshal(m, b)
}
func (m *DeactivatePolicyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivatePolicyCommand.Marshal(b, m, deterministic)
}
func (dst *DeactivatePolicyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivatePolicyCommand.Merge(dst, src)
}
func (m *DeactivatePolicyCommand) XXX_Size() int {
	return xxx_messageInfo_DeactivatePolicyCommand.Size(m)
}
func (m *DeactivatePolicyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivatePolicyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivatePolicyCommand proto.InternalMessageInfo

func (m *DeactivatePolicyCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *DeactivatePolicyCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *DeactivatePolicyCommand) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

type PolicyDeactivatedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyDeactivatedEvent) Reset()         { *m = PolicyDeactivatedEvent{} }
func (m *PolicyDeactivatedEvent) String() string { return proto.CompactTextString(m) }
func (*PolicyDeactivatedEvent) ProtoMessage()    {}
func (*PolicyDeactivatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{11}
}
func (m *PolicyDeactivatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyDeactivatedEvent.Unmarshal(m, b)
}
func (m *PolicyDeactivatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyDeactivatedEvent.Marshal(b, m, deterministic)
}
func (dst *PolicyDeactivatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyDeactivatedEvent.Merge(dst, src)
}
func (m *PolicyDeactivatedEvent) XXX_Size() int {
	return xxx_messageInfo_PolicyDeactivatedEvent.Size(m)
}
func (m *PolicyDeactivatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyDeactivatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyDeactivatedEvent proto.InternalMessageInfo

func (m *PolicyDeactivatedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PolicyDeactivatedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PolicyDeactivatedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

type AllowAreaPolicyCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowAreaPolicyCommand) Reset()         { *m = AllowAreaPolicyCommand{} }
func (m *AllowAreaPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*AllowAreaPolicyCommand) ProtoMessage()    {}
func (*AllowAreaPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{12}
}
func (m *AllowAreaPolicyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowAreaPolicyCommand.Unmarshal(m, b)
}
func (m *AllowAreaPolicyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowAreaPolicyCommand.Marshal(b, m, deterministic)
}
func (dst *AllowAreaPolicyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowAreaPolicyCommand.Merge(dst, src)
}
func (m *AllowAreaPolicyCommand) XXX_Size() int {
	return xxx_messageInfo_AllowAreaPolicyCommand.Size(m)
}
func (m *AllowAreaPolicyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowAreaPolicyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AllowAreaPolicyCommand proto.InternalMessageInfo

func (m *AllowAreaPolicyCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AllowAreaPolicyCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AllowAreaPolicyCommand) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AllowAreaPolicyCommand) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type AreaPolicyAllowedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaPolicyAllowedEvent) Reset()         { *m = AreaPolicyAllowedEvent{} }
func (m *AreaPolicyAllowedEvent) String() string { return proto.CompactTextString(m) }
func (*AreaPolicyAllowedEvent) ProtoMessage()    {}
func (*AreaPolicyAllowedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{13}
}
func (m *AreaPolicyAllowedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaPolicyAllowedEvent.Unmarshal(m, b)
}
func (m *AreaPolicyAllowedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaPolicyAllowedEvent.Marshal(b, m, deterministic)
}
func (dst *AreaPolicyAllowedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaPolicyAllowedEvent.Merge(dst, src)
}
func (m *AreaPolicyAllowedEvent) XXX_Size() int {
	return xxx_messageInfo_AreaPolicyAllowedEvent.Size(m)
}
func (m *AreaPolicyAllowedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaPolicyAllowedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AreaPolicyAllowedEvent proto.InternalMessageInfo

func (m *AreaPolicyAllowedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaPolicyAllowedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaPolicyAllowedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AreaPolicyAllowedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type DisallowAreaPolicyCommand struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisallowAreaPolicyCommand) Reset()         { *m = DisallowAreaPolicyCommand{} }
func (m *DisallowAreaPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*DisallowAreaPolicyCommand) ProtoMessage()    {}
func (*DisallowAreaPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{14}
}
func (m *DisallowAreaPolicyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisallowAreaPolicyCommand.Unmarshal(m, b)
}
func (m *DisallowAreaPolicyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisallowAreaPolicyCommand.Marshal(b, m, deterministic)
}
func (dst *DisallowAreaPolicyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisallowAreaPolicyCommand.Merge(dst, src)
}
func (m *DisallowAreaPolicyCommand) XXX_Size() int {
	return xxx_messageInfo_DisallowAreaPolicyCommand.Size(m)
}
func (m *DisallowAreaPolicyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DisallowAreaPolicyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DisallowAreaPolicyCommand proto.InternalMessageInfo

func (m *DisallowAreaPolicyCommand) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *DisallowAreaPolicyCommand) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *DisallowAreaPolicyCommand) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *DisallowAreaPolicyCommand) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type AreaPolicyDisallowedEvent struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaPolicyDisallowedEvent) Reset()         { *m = AreaPolicyDisallowedEvent{} }
func (m *AreaPolicyDisallowedEvent) String() string { return proto.CompactTextString(m) }
func (*AreaPolicyDisallowedEvent) ProtoMessage()    {}
func (*AreaPolicyDisallowedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_8073d076b75591a1, []int{15}
}
func (m *AreaPolicyDisallowedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaPolicyDisallowedEvent.Unmarshal(m, b)
}
func (m *AreaPolicyDisallowedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaPolicyDisallowedEvent.Marshal(b, m, deterministic)
}
func (dst *AreaPolicyDisallowedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaPolicyDisallowedEvent.Merge(dst, src)
}
func (m *AreaPolicyDisallowedEvent) XXX_Size() int {
	return xxx_messageInfo_AreaPolicyDisallowedEvent.Size(m)
}
func (m *AreaPolicyDisallowedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaPolicyDisallowedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AreaPolicyDisallowedEvent proto.InternalMessageInfo

func (m *AreaPolicyDisallowedEvent) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvent) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvent) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvent) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUnitCommand)(nil), "messages.CreateUnitCommand")
	proto.RegisterType((*UnitCreatedEvent)(nil), "messages.UnitCreatedEvent")
	proto.RegisterType((*GrantPrivilegeCommand)(nil), "messages.GrantPrivilegeCommand")
	proto.RegisterType((*PrivilegeGrantedEvent)(nil), "messages.PrivilegeGrantedEvent")
	proto.RegisterType((*RevokePrivilegeCommand)(nil), "messages.RevokePrivilegeCommand")
	proto.RegisterType((*PrivilegeRevokedEvent)(nil), "messages.PrivilegeRevokedEvent")
	proto.RegisterType((*CreateAreaCommand)(nil), "messages.CreateAreaCommand")
	proto.RegisterType((*AreaCreatedEvent)(nil), "messages.AreaCreatedEvent")
	proto.RegisterType((*CreatePolicyCommand)(nil), "messages.CreatePolicyCommand")
	proto.RegisterType((*PolicyCreatedEvent)(nil), "messages.PolicyCreatedEvent")
	proto.RegisterType((*DeactivatePolicyCommand)(nil), "messages.DeactivatePolicyCommand")
	proto.RegisterType((*PolicyDeactivatedEvent)(nil), "messages.PolicyDeactivatedEvent")
	proto.RegisterType((*AllowAreaPolicyCommand)(nil), "messages.AllowAreaPolicyCommand")
	proto.RegisterType((*AreaPolicyAllowedEvent)(nil), "messages.AreaPolicyAllowedEvent")
	proto.RegisterType((*DisallowAreaPolicyCommand)(nil), "messages.DisallowAreaPolicyCommand")
	proto.RegisterType((*AreaPolicyDisallowedEvent)(nil), "messages.AreaPolicyDisallowedEvent")
}

func init() {
	proto.RegisterFile("messages/unit_aggregate.proto", fileDescriptor_unit_aggregate_8073d076b75591a1)
}

var fileDescriptor_unit_aggregate_8073d076b75591a1 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xfb, 0x73, 0xd3, 0x74, 0xfa, 0x2b, 0x94, 0x2d, 0x04, 0xb7, 0x02, 0x29, 0xea, 0x01,
	0x45, 0x1c, 0x0a, 0x82, 0x1b, 0xb7, 0xa8, 0x46, 0x28, 0x12, 0xa9, 0x82, 0xa5, 0x96, 0x63, 0xb5,
	0x75, 0xa6, 0x66, 0x45, 0xbc, 0x2e, 0xbb, 0xeb, 0xf0, 0xef, 0xc6, 0x85, 0x33, 0x48, 0x5c, 0xf8,
	0x00, 0xf0, 0x1d, 0xe0, 0x02, 0xdf, 0x0c, 0x79, 0xd7, 0xb1, 0xe3, 0xd8, 0x95, 0x2a, 0xe5, 0x0f,
	0x54, 0x70, 0xcb, 0xcc, 0xbc, 0xb7, 0xfb, 0xf6, 0xed, 0xec, 0x58, 0x81, 0x9b, 0x21, 0x4a, 0x49,
	0x03, 0x94, 0x77, 0x62, 0xce, 0xd4, 0x11, 0x0d, 0x02, 0x81, 0x01, 0x55, 0xb8, 0x7b, 0x2a, 0x22,
	0x15, 0x91, 0xfa, 0xa8, 0xbc, 0x7d, 0x23, 0x03, 0xfa, 0xb1, 0x54, 0x51, 0x78, 0x74, 0xc2, 0x70,
	0xd0, 0x97, 0x06, 0xb7, 0xf3, 0xdd, 0x82, 0x2b, 0x7b, 0x02, 0xa9, 0xc2, 0x03, 0xce, 0xd4, 0x5e,
	0x14, 0x86, 0x94, 0xf7, 0x49, 0x03, 0x6a, 0x49, 0xd8, 0x71, 0x1d, 0xab, 0x69, 0xb5, 0x56, 0xbd,
	0x34, 0x22, 0x4d, 0x58, 0xf3, 0xf0, 0x45, 0x8c, 0x52, 0xa1, 0xe8, 0xb8, 0xce, 0x92, 0x2e, 0x8e,
	0xa7, 0x08, 0x01, 0x7b, 0x9f, 0x86, 0xe8, 0xfc, 0xa7, 0x4b, 0xfa, 0x77, 0xc2, 0x72, 0x51, 0xfa,
	0x82, 0x9d, 0x2a, 0x16, 0x71, 0xc7, 0x36, 0xac, 0xb1, 0x14, 0xb9, 0x0d, 0x1b, 0x07, 0xde, 0xe3,
	0x1e, 0x15, 0x34, 0x44, 0x85, 0x42, 0xaf, 0xb0, 0xac, 0x61, 0xa5, 0xfc, 0x03, 0xf8, 0xfc, 0x6e,
	0x2b, 0xd5, 0xb3, 0xf3, 0xcd, 0x82, 0x0d, 0xad, 0x5b, 0x9f, 0xa0, 0xff, 0x70, 0x88, 0x5c, 0x5d,
	0x18, 0xf1, 0xef, 0x97, 0xe0, 0xda, 0x23, 0x41, 0xb9, 0xea, 0x09, 0x36, 0x64, 0x03, 0x0c, 0x70,
	0x7a, 0xfb, 0xb7, 0xa1, 0xde, 0xc5, 0xf0, 0x58, 0x97, 0xcd, 0x29, 0xb2, 0x38, 0x61, 0x1f, 0x46,
	0x8a, 0xf1, 0xc0, 0x63, 0xc1, 0x33, 0xa5, 0x25, 0xd6, 0xbd, 0xf1, 0x14, 0x69, 0xc1, 0xe5, 0x0e,
	0x67, 0x8a, 0x51, 0xc5, 0x86, 0x68, 0x50, 0x35, 0x8d, 0x9a, 0x4c, 0x27, 0xc8, 0x2e, 0xe5, 0x34,
	0xc0, 0x10, 0xb9, 0x32, 0xc8, 0x15, 0x83, 0x9c, 0x48, 0x27, 0x67, 0x79, 0x8a, 0x1a, 0x50, 0x6f,
	0x5a, 0xad, 0x75, 0x2f, 0x8d, 0x4a, 0x4e, 0x64, 0x26, 0x68, 0x4b, 0xa6, 0xbf, 0xcb, 0x8b, 0xe9,
	0xc4, 0x1b, 0x68, 0x78, 0x38, 0x8c, 0x9e, 0xe3, 0x62, 0x7a, 0xa2, 0xb0, 0xf7, 0x07, 0x6b, 0xec,
	0x16, 0x8c, 0x8a, 0xb9, 0xde, 0x42, 0xee, 0x87, 0x7d, 0xa6, 0x1f, 0x5f, 0xb3, 0xf1, 0xd4, 0x16,
	0x48, 0xa7, 0xf7, 0xa2, 0x01, 0xb5, 0x64, 0xa1, 0x4c, 0x4d, 0x1a, 0x65, 0x2f, 0xdf, 0x3e, 0xfb,
	0xe5, 0x2f, 0x97, 0x5e, 0x7e, 0x41, 0xe9, 0x17, 0x0b, 0x36, 0xb4, 0xc6, 0xd9, 0x8c, 0xa2, 0xf9,
	0x09, 0xfd, 0x69, 0xc3, 0xa6, 0x11, 0xd9, 0x8b, 0x06, 0xcc, 0x7f, 0x3d, 0x93, 0x06, 0x33, 0x4b,
	0xe5, 0x97, 0x3c, 0x8a, 0xcf, 0x31, 0x3e, 0xef, 0xc1, 0xd5, 0x2e, 0xe3, 0xed, 0x7e, 0xc8, 0xa4,
	0x64, 0x11, 0x77, 0x63, 0x41, 0xb3, 0x63, 0x2c, 0x7b, 0x95, 0x35, 0xcd, 0xa1, 0xaf, 0xca, 0x9c,
	0x5a, 0xca, 0xa9, 0xa8, 0x91, 0x5d, 0x20, 0x2e, 0x93, 0x7e, 0x5c, 0x64, 0xac, 0x68, 0x46, 0x45,
	0x25, 0xd9, 0xe3, 0x10, 0x05, 0x3b, 0x61, 0xbe, 0x8e, 0x33, 0x46, 0xdd, 0xec, 0x51, 0x55, 0x23,
	0xb7, 0xe0, 0x92, 0x99, 0x22, 0x19, 0x7a, 0x55, 0xa3, 0x27, 0xb2, 0x09, 0xae, 0x23, 0x65, 0x8c,
	0x4f, 0xe2, 0x48, 0xc4, 0xe1, 0x7e, 0x1c, 0x3a, 0x60, 0x70, 0xc5, 0xec, 0x04, 0xce, 0x45, 0xee,
	0xac, 0x95, 0x70, 0x2e, 0x72, 0x72, 0x17, 0x36, 0xf3, 0xb9, 0x94, 0x2f, 0xfa, 0xbf, 0x06, 0x57,
	0x95, 0xaa, 0x18, 0xc9, 0xf2, 0xeb, 0xd5, 0x0c, 0x17, 0x8b, 0x3d, 0xf4, 0xc3, 0x06, 0x92, 0x76,
	0xcf, 0x6c, 0xda, 0xfd, 0x5f, 0x0b, 0xfd, 0x6d, 0x2d, 0xf4, 0x16, 0xae, 0xbb, 0x48, 0x7d, 0xc5,
	0x86, 0x8b, 0x99, 0x44, 0x93, 0x9f, 0x59, 0x93, 0xcf, 0x25, 0xcc, 0xb3, 0x85, 0x0b, 0x7b, 0x7f,
	0xb4, 0xa0, 0xd1, 0x1e, 0x0c, 0xa2, 0x97, 0xc9, 0x44, 0x5f, 0xc4, 0x08, 0xce, 0x3f, 0x25, 0xf6,
	0xf8, 0xa7, 0xa4, 0x2c, 0x2a, 0xd3, 0xa3, 0xe5, 0xcd, 0xf7, 0x51, 0x9f, 0x47, 0xd4, 0x27, 0x0b,
	0xb6, 0x5c, 0x26, 0xe9, 0x9f, 0x66, 0x56, 0xa2, 0x2b, 0xd7, 0x33, 0x52, 0xf8, 0xdb, 0xfd, 0x3a,
	0xae, 0xe9, 0xbf, 0x74, 0xf7, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x78, 0xc2, 0x0a, 0x6c, 0x1b,
	0x0e, 0x00, 0x00,
}
