// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/unit_aggregate.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUnitCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitCmd) Reset()         { *m = CreateUnitCmd{} }
func (m *CreateUnitCmd) String() string { return proto.CompactTextString(m) }
func (*CreateUnitCmd) ProtoMessage()    {}
func (*CreateUnitCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{0}
}
func (m *CreateUnitCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitCmd.Unmarshal(m, b)
}
func (m *CreateUnitCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitCmd.Marshal(b, m, deterministic)
}
func (dst *CreateUnitCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitCmd.Merge(dst, src)
}
func (m *CreateUnitCmd) XXX_Size() int {
	return xxx_messageInfo_CreateUnitCmd.Size(m)
}
func (m *CreateUnitCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitCmd proto.InternalMessageInfo

func (m *CreateUnitCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateUnitCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateUnitCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUnitCmd) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUnitCmd) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type UnitCreatedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	URLParameterName     string   `protobuf:"bytes,5,opt,name=URLParameterName,proto3" json:"URLParameterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitCreatedEvt) Reset()         { *m = UnitCreatedEvt{} }
func (m *UnitCreatedEvt) String() string { return proto.CompactTextString(m) }
func (*UnitCreatedEvt) ProtoMessage()    {}
func (*UnitCreatedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{1}
}
func (m *UnitCreatedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitCreatedEvt.Unmarshal(m, b)
}
func (m *UnitCreatedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitCreatedEvt.Marshal(b, m, deterministic)
}
func (dst *UnitCreatedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitCreatedEvt.Merge(dst, src)
}
func (m *UnitCreatedEvt) XXX_Size() int {
	return xxx_messageInfo_UnitCreatedEvt.Size(m)
}
func (m *UnitCreatedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitCreatedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_UnitCreatedEvt proto.InternalMessageInfo

func (m *UnitCreatedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *UnitCreatedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *UnitCreatedEvt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnitCreatedEvt) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UnitCreatedEvt) GetURLParameterName() string {
	if m != nil {
		return m.URLParameterName
	}
	return ""
}

type GrantPrivilegeCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPrivilegeCmd) Reset()         { *m = GrantPrivilegeCmd{} }
func (m *GrantPrivilegeCmd) String() string { return proto.CompactTextString(m) }
func (*GrantPrivilegeCmd) ProtoMessage()    {}
func (*GrantPrivilegeCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{2}
}
func (m *GrantPrivilegeCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPrivilegeCmd.Unmarshal(m, b)
}
func (m *GrantPrivilegeCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPrivilegeCmd.Marshal(b, m, deterministic)
}
func (dst *GrantPrivilegeCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPrivilegeCmd.Merge(dst, src)
}
func (m *GrantPrivilegeCmd) XXX_Size() int {
	return xxx_messageInfo_GrantPrivilegeCmd.Size(m)
}
func (m *GrantPrivilegeCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPrivilegeCmd.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPrivilegeCmd proto.InternalMessageInfo

func (m *GrantPrivilegeCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *GrantPrivilegeCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *GrantPrivilegeCmd) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *GrantPrivilegeCmd) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *GrantPrivilegeCmd) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *GrantPrivilegeCmd) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *GrantPrivilegeCmd) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type PrivilegeGrantedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	VotingRight          bool     `protobuf:"varint,5,opt,name=VotingRight,proto3" json:"VotingRight,omitempty"`
	InitiativeRight      bool     `protobuf:"varint,6,opt,name=InitiativeRight,proto3" json:"InitiativeRight,omitempty"`
	ManagementRight      bool     `protobuf:"varint,7,opt,name=ManagementRight,proto3" json:"ManagementRight,omitempty"`
	Weight               uint32   `protobuf:"varint,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeGrantedEvt) Reset()         { *m = PrivilegeGrantedEvt{} }
func (m *PrivilegeGrantedEvt) String() string { return proto.CompactTextString(m) }
func (*PrivilegeGrantedEvt) ProtoMessage()    {}
func (*PrivilegeGrantedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{3}
}
func (m *PrivilegeGrantedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeGrantedEvt.Unmarshal(m, b)
}
func (m *PrivilegeGrantedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeGrantedEvt.Marshal(b, m, deterministic)
}
func (dst *PrivilegeGrantedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeGrantedEvt.Merge(dst, src)
}
func (m *PrivilegeGrantedEvt) XXX_Size() int {
	return xxx_messageInfo_PrivilegeGrantedEvt.Size(m)
}
func (m *PrivilegeGrantedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeGrantedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeGrantedEvt proto.InternalMessageInfo

func (m *PrivilegeGrantedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeGrantedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeGrantedEvt) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeGrantedEvt) GetVotingRight() bool {
	if m != nil {
		return m.VotingRight
	}
	return false
}

func (m *PrivilegeGrantedEvt) GetInitiativeRight() bool {
	if m != nil {
		return m.InitiativeRight
	}
	return false
}

func (m *PrivilegeGrantedEvt) GetManagementRight() bool {
	if m != nil {
		return m.ManagementRight
	}
	return false
}

func (m *PrivilegeGrantedEvt) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type RevokePrivilegeCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePrivilegeCmd) Reset()         { *m = RevokePrivilegeCmd{} }
func (m *RevokePrivilegeCmd) String() string { return proto.CompactTextString(m) }
func (*RevokePrivilegeCmd) ProtoMessage()    {}
func (*RevokePrivilegeCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{4}
}
func (m *RevokePrivilegeCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePrivilegeCmd.Unmarshal(m, b)
}
func (m *RevokePrivilegeCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePrivilegeCmd.Marshal(b, m, deterministic)
}
func (dst *RevokePrivilegeCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePrivilegeCmd.Merge(dst, src)
}
func (m *RevokePrivilegeCmd) XXX_Size() int {
	return xxx_messageInfo_RevokePrivilegeCmd.Size(m)
}
func (m *RevokePrivilegeCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePrivilegeCmd.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePrivilegeCmd proto.InternalMessageInfo

func (m *RevokePrivilegeCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *RevokePrivilegeCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *RevokePrivilegeCmd) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

type PrivilegeRevokedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	MemberID             string   `protobuf:"bytes,3,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	Weight               uint32   `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivilegeRevokedEvt) Reset()         { *m = PrivilegeRevokedEvt{} }
func (m *PrivilegeRevokedEvt) String() string { return proto.CompactTextString(m) }
func (*PrivilegeRevokedEvt) ProtoMessage()    {}
func (*PrivilegeRevokedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{5}
}
func (m *PrivilegeRevokedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeRevokedEvt.Unmarshal(m, b)
}
func (m *PrivilegeRevokedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeRevokedEvt.Marshal(b, m, deterministic)
}
func (dst *PrivilegeRevokedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeRevokedEvt.Merge(dst, src)
}
func (m *PrivilegeRevokedEvt) XXX_Size() int {
	return xxx_messageInfo_PrivilegeRevokedEvt.Size(m)
}
func (m *PrivilegeRevokedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeRevokedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeRevokedEvt proto.InternalMessageInfo

func (m *PrivilegeRevokedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PrivilegeRevokedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PrivilegeRevokedEvt) GetMemberID() string {
	if m != nil {
		return m.MemberID
	}
	return ""
}

func (m *PrivilegeRevokedEvt) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type CreateAreaCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAreaCmd) Reset()         { *m = CreateAreaCmd{} }
func (m *CreateAreaCmd) String() string { return proto.CompactTextString(m) }
func (*CreateAreaCmd) ProtoMessage()    {}
func (*CreateAreaCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{6}
}
func (m *CreateAreaCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAreaCmd.Unmarshal(m, b)
}
func (m *CreateAreaCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAreaCmd.Marshal(b, m, deterministic)
}
func (dst *CreateAreaCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAreaCmd.Merge(dst, src)
}
func (m *CreateAreaCmd) XXX_Size() int {
	return xxx_messageInfo_CreateAreaCmd.Size(m)
}
func (m *CreateAreaCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAreaCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAreaCmd proto.InternalMessageInfo

func (m *CreateAreaCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreateAreaCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreateAreaCmd) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *CreateAreaCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAreaCmd) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AreaCreatedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	AreaID               string   `protobuf:"bytes,3,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaCreatedEvt) Reset()         { *m = AreaCreatedEvt{} }
func (m *AreaCreatedEvt) String() string { return proto.CompactTextString(m) }
func (*AreaCreatedEvt) ProtoMessage()    {}
func (*AreaCreatedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{7}
}
func (m *AreaCreatedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaCreatedEvt.Unmarshal(m, b)
}
func (m *AreaCreatedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaCreatedEvt.Marshal(b, m, deterministic)
}
func (dst *AreaCreatedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaCreatedEvt.Merge(dst, src)
}
func (m *AreaCreatedEvt) XXX_Size() int {
	return xxx_messageInfo_AreaCreatedEvt.Size(m)
}
func (m *AreaCreatedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaCreatedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_AreaCreatedEvt proto.InternalMessageInfo

func (m *AreaCreatedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaCreatedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaCreatedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func (m *AreaCreatedEvt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaCreatedEvt) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreatePolicyCmd struct {
	UnitID      string `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID string `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID    string `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	// Max / min amount of time before an issue is passed the Admision phase
	MinAdmissionDuration int32 `protobuf:"varint,5,opt,name=MinAdmissionDuration,proto3" json:"MinAdmissionDuration,omitempty"`
	MaxAdmissionDuration int32 `protobuf:"varint,6,opt,name=MaxAdmissionDuration,proto3" json:"MaxAdmissionDuration,omitempty"`
	// phase durations
	DiscussionDuration   int32 `protobuf:"varint,7,opt,name=DiscussionDuration,proto3" json:"DiscussionDuration,omitempty"`
	VerificationDuration int32 `protobuf:"varint,8,opt,name=VerificationDuration,proto3" json:"VerificationDuration,omitempty"`
	VotingDuration       int32 `protobuf:"varint,9,opt,name=VotingDuration,proto3" json:"VotingDuration,omitempty"`
	// quorums required (numerator / denominator)
	IssueQuorumNum       int32    `protobuf:"varint,10,opt,name=IssueQuorumNum,proto3" json:"IssueQuorumNum,omitempty"`
	IssueQuorumDen       int32    `protobuf:"varint,11,opt,name=IssueQuorumDen,proto3" json:"IssueQuorumDen,omitempty"`
	InitiativeQuorumNum  int32    `protobuf:"varint,12,opt,name=InitiativeQuorumNum,proto3" json:"InitiativeQuorumNum,omitempty"`
	InitiativeQuorumDen  int32    `protobuf:"varint,13,opt,name=InitiativeQuorumDen,proto3" json:"InitiativeQuorumDen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyCmd) Reset()         { *m = CreatePolicyCmd{} }
func (m *CreatePolicyCmd) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyCmd) ProtoMessage()    {}
func (*CreatePolicyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{8}
}
func (m *CreatePolicyCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyCmd.Unmarshal(m, b)
}
func (m *CreatePolicyCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyCmd.Marshal(b, m, deterministic)
}
func (dst *CreatePolicyCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyCmd.Merge(dst, src)
}
func (m *CreatePolicyCmd) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyCmd.Size(m)
}
func (m *CreatePolicyCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyCmd proto.InternalMessageInfo

func (m *CreatePolicyCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *CreatePolicyCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *CreatePolicyCmd) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *CreatePolicyCmd) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePolicyCmd) GetMinAdmissionDuration() int32 {
	if m != nil {
		return m.MinAdmissionDuration
	}
	return 0
}

func (m *CreatePolicyCmd) GetMaxAdmissionDuration() int32 {
	if m != nil {
		return m.MaxAdmissionDuration
	}
	return 0
}

func (m *CreatePolicyCmd) GetDiscussionDuration() int32 {
	if m != nil {
		return m.DiscussionDuration
	}
	return 0
}

func (m *CreatePolicyCmd) GetVerificationDuration() int32 {
	if m != nil {
		return m.VerificationDuration
	}
	return 0
}

func (m *CreatePolicyCmd) GetVotingDuration() int32 {
	if m != nil {
		return m.VotingDuration
	}
	return 0
}

func (m *CreatePolicyCmd) GetIssueQuorumNum() int32 {
	if m != nil {
		return m.IssueQuorumNum
	}
	return 0
}

func (m *CreatePolicyCmd) GetIssueQuorumDen() int32 {
	if m != nil {
		return m.IssueQuorumDen
	}
	return 0
}

func (m *CreatePolicyCmd) GetInitiativeQuorumNum() int32 {
	if m != nil {
		return m.InitiativeQuorumNum
	}
	return 0
}

func (m *CreatePolicyCmd) GetInitiativeQuorumDen() int32 {
	if m != nil {
		return m.InitiativeQuorumDen
	}
	return 0
}

type PolicyCreatedEvt struct {
	UnitID      string `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID string `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID    string `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	// Max / min amount of time before an issue is passed the Admision phase
	MinAdmissionDuration int32 `protobuf:"varint,5,opt,name=MinAdmissionDuration,proto3" json:"MinAdmissionDuration,omitempty"`
	MaxAdmissionDuration int32 `protobuf:"varint,6,opt,name=MaxAdmissionDuration,proto3" json:"MaxAdmissionDuration,omitempty"`
	// phase durations
	DiscussionDuration   int32 `protobuf:"varint,7,opt,name=DiscussionDuration,proto3" json:"DiscussionDuration,omitempty"`
	VerificationDuration int32 `protobuf:"varint,8,opt,name=VerificationDuration,proto3" json:"VerificationDuration,omitempty"`
	VotingDuration       int32 `protobuf:"varint,9,opt,name=VotingDuration,proto3" json:"VotingDuration,omitempty"`
	// quorums required (numerator / denominator)
	IssueQuorumNum       int32    `protobuf:"varint,10,opt,name=IssueQuorumNum,proto3" json:"IssueQuorumNum,omitempty"`
	IssueQuorumDen       int32    `protobuf:"varint,11,opt,name=IssueQuorumDen,proto3" json:"IssueQuorumDen,omitempty"`
	InitiativeQuorumNum  int32    `protobuf:"varint,12,opt,name=InitiativeQuorumNum,proto3" json:"InitiativeQuorumNum,omitempty"`
	InitiativeQuorumDen  int32    `protobuf:"varint,13,opt,name=InitiativeQuorumDen,proto3" json:"InitiativeQuorumDen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyCreatedEvt) Reset()         { *m = PolicyCreatedEvt{} }
func (m *PolicyCreatedEvt) String() string { return proto.CompactTextString(m) }
func (*PolicyCreatedEvt) ProtoMessage()    {}
func (*PolicyCreatedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{9}
}
func (m *PolicyCreatedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyCreatedEvt.Unmarshal(m, b)
}
func (m *PolicyCreatedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyCreatedEvt.Marshal(b, m, deterministic)
}
func (dst *PolicyCreatedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyCreatedEvt.Merge(dst, src)
}
func (m *PolicyCreatedEvt) XXX_Size() int {
	return xxx_messageInfo_PolicyCreatedEvt.Size(m)
}
func (m *PolicyCreatedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyCreatedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyCreatedEvt proto.InternalMessageInfo

func (m *PolicyCreatedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PolicyCreatedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PolicyCreatedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *PolicyCreatedEvt) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PolicyCreatedEvt) GetMinAdmissionDuration() int32 {
	if m != nil {
		return m.MinAdmissionDuration
	}
	return 0
}

func (m *PolicyCreatedEvt) GetMaxAdmissionDuration() int32 {
	if m != nil {
		return m.MaxAdmissionDuration
	}
	return 0
}

func (m *PolicyCreatedEvt) GetDiscussionDuration() int32 {
	if m != nil {
		return m.DiscussionDuration
	}
	return 0
}

func (m *PolicyCreatedEvt) GetVerificationDuration() int32 {
	if m != nil {
		return m.VerificationDuration
	}
	return 0
}

func (m *PolicyCreatedEvt) GetVotingDuration() int32 {
	if m != nil {
		return m.VotingDuration
	}
	return 0
}

func (m *PolicyCreatedEvt) GetIssueQuorumNum() int32 {
	if m != nil {
		return m.IssueQuorumNum
	}
	return 0
}

func (m *PolicyCreatedEvt) GetIssueQuorumDen() int32 {
	if m != nil {
		return m.IssueQuorumDen
	}
	return 0
}

func (m *PolicyCreatedEvt) GetInitiativeQuorumNum() int32 {
	if m != nil {
		return m.InitiativeQuorumNum
	}
	return 0
}

func (m *PolicyCreatedEvt) GetInitiativeQuorumDen() int32 {
	if m != nil {
		return m.InitiativeQuorumDen
	}
	return 0
}

type DeactivatePolicyCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivatePolicyCmd) Reset()         { *m = DeactivatePolicyCmd{} }
func (m *DeactivatePolicyCmd) String() string { return proto.CompactTextString(m) }
func (*DeactivatePolicyCmd) ProtoMessage()    {}
func (*DeactivatePolicyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{10}
}
func (m *DeactivatePolicyCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivatePolicyCmd.Unmarshal(m, b)
}
func (m *DeactivatePolicyCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivatePolicyCmd.Marshal(b, m, deterministic)
}
func (dst *DeactivatePolicyCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivatePolicyCmd.Merge(dst, src)
}
func (m *DeactivatePolicyCmd) XXX_Size() int {
	return xxx_messageInfo_DeactivatePolicyCmd.Size(m)
}
func (m *DeactivatePolicyCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivatePolicyCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivatePolicyCmd proto.InternalMessageInfo

func (m *DeactivatePolicyCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *DeactivatePolicyCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *DeactivatePolicyCmd) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

type PolicyDeactivatedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyDeactivatedEvt) Reset()         { *m = PolicyDeactivatedEvt{} }
func (m *PolicyDeactivatedEvt) String() string { return proto.CompactTextString(m) }
func (*PolicyDeactivatedEvt) ProtoMessage()    {}
func (*PolicyDeactivatedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{11}
}
func (m *PolicyDeactivatedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyDeactivatedEvt.Unmarshal(m, b)
}
func (m *PolicyDeactivatedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyDeactivatedEvt.Marshal(b, m, deterministic)
}
func (dst *PolicyDeactivatedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyDeactivatedEvt.Merge(dst, src)
}
func (m *PolicyDeactivatedEvt) XXX_Size() int {
	return xxx_messageInfo_PolicyDeactivatedEvt.Size(m)
}
func (m *PolicyDeactivatedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyDeactivatedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyDeactivatedEvt proto.InternalMessageInfo

func (m *PolicyDeactivatedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *PolicyDeactivatedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *PolicyDeactivatedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

type AllowAreaPolicyCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowAreaPolicyCmd) Reset()         { *m = AllowAreaPolicyCmd{} }
func (m *AllowAreaPolicyCmd) String() string { return proto.CompactTextString(m) }
func (*AllowAreaPolicyCmd) ProtoMessage()    {}
func (*AllowAreaPolicyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{12}
}
func (m *AllowAreaPolicyCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowAreaPolicyCmd.Unmarshal(m, b)
}
func (m *AllowAreaPolicyCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowAreaPolicyCmd.Marshal(b, m, deterministic)
}
func (dst *AllowAreaPolicyCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowAreaPolicyCmd.Merge(dst, src)
}
func (m *AllowAreaPolicyCmd) XXX_Size() int {
	return xxx_messageInfo_AllowAreaPolicyCmd.Size(m)
}
func (m *AllowAreaPolicyCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowAreaPolicyCmd.DiscardUnknown(m)
}

var xxx_messageInfo_AllowAreaPolicyCmd proto.InternalMessageInfo

func (m *AllowAreaPolicyCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AllowAreaPolicyCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AllowAreaPolicyCmd) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AllowAreaPolicyCmd) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type AreaPolicyAllowedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaPolicyAllowedEvt) Reset()         { *m = AreaPolicyAllowedEvt{} }
func (m *AreaPolicyAllowedEvt) String() string { return proto.CompactTextString(m) }
func (*AreaPolicyAllowedEvt) ProtoMessage()    {}
func (*AreaPolicyAllowedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{13}
}
func (m *AreaPolicyAllowedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaPolicyAllowedEvt.Unmarshal(m, b)
}
func (m *AreaPolicyAllowedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaPolicyAllowedEvt.Marshal(b, m, deterministic)
}
func (dst *AreaPolicyAllowedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaPolicyAllowedEvt.Merge(dst, src)
}
func (m *AreaPolicyAllowedEvt) XXX_Size() int {
	return xxx_messageInfo_AreaPolicyAllowedEvt.Size(m)
}
func (m *AreaPolicyAllowedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaPolicyAllowedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_AreaPolicyAllowedEvt proto.InternalMessageInfo

func (m *AreaPolicyAllowedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaPolicyAllowedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaPolicyAllowedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AreaPolicyAllowedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type DisallowAreaPolicyCmd struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisallowAreaPolicyCmd) Reset()         { *m = DisallowAreaPolicyCmd{} }
func (m *DisallowAreaPolicyCmd) String() string { return proto.CompactTextString(m) }
func (*DisallowAreaPolicyCmd) ProtoMessage()    {}
func (*DisallowAreaPolicyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{14}
}
func (m *DisallowAreaPolicyCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisallowAreaPolicyCmd.Unmarshal(m, b)
}
func (m *DisallowAreaPolicyCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisallowAreaPolicyCmd.Marshal(b, m, deterministic)
}
func (dst *DisallowAreaPolicyCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisallowAreaPolicyCmd.Merge(dst, src)
}
func (m *DisallowAreaPolicyCmd) XXX_Size() int {
	return xxx_messageInfo_DisallowAreaPolicyCmd.Size(m)
}
func (m *DisallowAreaPolicyCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DisallowAreaPolicyCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DisallowAreaPolicyCmd proto.InternalMessageInfo

func (m *DisallowAreaPolicyCmd) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *DisallowAreaPolicyCmd) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *DisallowAreaPolicyCmd) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *DisallowAreaPolicyCmd) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

type AreaPolicyDisallowedEvt struct {
	UnitID               string   `protobuf:"bytes,1,opt,name=UnitID,proto3" json:"UnitID,omitempty"`
	RequesterID          string   `protobuf:"bytes,2,opt,name=RequesterID,proto3" json:"RequesterID,omitempty"`
	PolicyID             string   `protobuf:"bytes,3,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	AreaID               string   `protobuf:"bytes,4,opt,name=AreaID,proto3" json:"AreaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaPolicyDisallowedEvt) Reset()         { *m = AreaPolicyDisallowedEvt{} }
func (m *AreaPolicyDisallowedEvt) String() string { return proto.CompactTextString(m) }
func (*AreaPolicyDisallowedEvt) ProtoMessage()    {}
func (*AreaPolicyDisallowedEvt) Descriptor() ([]byte, []int) {
	return fileDescriptor_unit_aggregate_5e3543043b14b8be, []int{15}
}
func (m *AreaPolicyDisallowedEvt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaPolicyDisallowedEvt.Unmarshal(m, b)
}
func (m *AreaPolicyDisallowedEvt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaPolicyDisallowedEvt.Marshal(b, m, deterministic)
}
func (dst *AreaPolicyDisallowedEvt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaPolicyDisallowedEvt.Merge(dst, src)
}
func (m *AreaPolicyDisallowedEvt) XXX_Size() int {
	return xxx_messageInfo_AreaPolicyDisallowedEvt.Size(m)
}
func (m *AreaPolicyDisallowedEvt) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaPolicyDisallowedEvt.DiscardUnknown(m)
}

var xxx_messageInfo_AreaPolicyDisallowedEvt proto.InternalMessageInfo

func (m *AreaPolicyDisallowedEvt) GetUnitID() string {
	if m != nil {
		return m.UnitID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvt) GetRequesterID() string {
	if m != nil {
		return m.RequesterID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvt) GetPolicyID() string {
	if m != nil {
		return m.PolicyID
	}
	return ""
}

func (m *AreaPolicyDisallowedEvt) GetAreaID() string {
	if m != nil {
		return m.AreaID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUnitCmd)(nil), "messages.CreateUnitCmd")
	proto.RegisterType((*UnitCreatedEvt)(nil), "messages.UnitCreatedEvt")
	proto.RegisterType((*GrantPrivilegeCmd)(nil), "messages.GrantPrivilegeCmd")
	proto.RegisterType((*PrivilegeGrantedEvt)(nil), "messages.PrivilegeGrantedEvt")
	proto.RegisterType((*RevokePrivilegeCmd)(nil), "messages.RevokePrivilegeCmd")
	proto.RegisterType((*PrivilegeRevokedEvt)(nil), "messages.PrivilegeRevokedEvt")
	proto.RegisterType((*CreateAreaCmd)(nil), "messages.CreateAreaCmd")
	proto.RegisterType((*AreaCreatedEvt)(nil), "messages.AreaCreatedEvt")
	proto.RegisterType((*CreatePolicyCmd)(nil), "messages.CreatePolicyCmd")
	proto.RegisterType((*PolicyCreatedEvt)(nil), "messages.PolicyCreatedEvt")
	proto.RegisterType((*DeactivatePolicyCmd)(nil), "messages.DeactivatePolicyCmd")
	proto.RegisterType((*PolicyDeactivatedEvt)(nil), "messages.PolicyDeactivatedEvt")
	proto.RegisterType((*AllowAreaPolicyCmd)(nil), "messages.AllowAreaPolicyCmd")
	proto.RegisterType((*AreaPolicyAllowedEvt)(nil), "messages.AreaPolicyAllowedEvt")
	proto.RegisterType((*DisallowAreaPolicyCmd)(nil), "messages.DisallowAreaPolicyCmd")
	proto.RegisterType((*AreaPolicyDisallowedEvt)(nil), "messages.AreaPolicyDisallowedEvt")
}

func init() {
	proto.RegisterFile("messages/unit_aggregate.proto", fileDescriptor_unit_aggregate_5e3543043b14b8be)
}

var fileDescriptor_unit_aggregate_5e3543043b14b8be = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x8b, 0x9b, 0xa6, 0x53, 0xfa, 0xc1, 0xb6, 0x14, 0x53, 0x81, 0x54, 0xf5, 0x80, 0x22,
	0x0e, 0x05, 0xc1, 0x8d, 0x5b, 0x54, 0x23, 0x14, 0x89, 0x54, 0xc1, 0x52, 0xcb, 0xb1, 0xda, 0x3a,
	0x53, 0xb3, 0x22, 0x5e, 0x97, 0xdd, 0xb5, 0x5b, 0xae, 0x20, 0xae, 0x7c, 0x88, 0x1b, 0x57, 0xf8,
	0x0f, 0x70, 0x81, 0xdf, 0x86, 0xbc, 0xeb, 0xd8, 0x71, 0xe2, 0x4a, 0x95, 0x52, 0x0b, 0x2a, 0xb8,
	0x65, 0x66, 0xde, 0xdb, 0x79, 0x7e, 0x9e, 0x1d, 0x2b, 0x70, 0x3b, 0x44, 0x29, 0x69, 0x80, 0xf2,
	0x5e, 0xcc, 0x99, 0x3a, 0xa0, 0x41, 0x20, 0x30, 0xa0, 0x0a, 0xb7, 0x8f, 0x45, 0xa4, 0x22, 0xd2,
	0x1c, 0x96, 0x37, 0x6e, 0xe5, 0x40, 0x3f, 0x96, 0x2a, 0x0a, 0x0f, 0x8e, 0x18, 0x0e, 0xfa, 0xd2,
	0xe0, 0xb6, 0xbe, 0x5b, 0xb0, 0xb8, 0x23, 0x90, 0x2a, 0xdc, 0xe3, 0x4c, 0xed, 0x84, 0x7d, 0xb2,
	0x0e, 0x8d, 0xf4, 0x67, 0xc7, 0x75, 0xac, 0x4d, 0xab, 0x35, 0xef, 0x65, 0x11, 0xd9, 0x84, 0x05,
	0x0f, 0x5f, 0xc5, 0x28, 0x15, 0x8a, 0x8e, 0xeb, 0xcc, 0xe8, 0xe2, 0x68, 0x8a, 0x10, 0xb0, 0x77,
	0x69, 0x88, 0xce, 0x15, 0x5d, 0xd2, 0xbf, 0x53, 0x96, 0x8b, 0xd2, 0x17, 0xec, 0x58, 0xb1, 0x88,
	0x3b, 0xb6, 0x61, 0x8d, 0xa4, 0xc8, 0x5d, 0x58, 0xd9, 0xf3, 0x9e, 0xf6, 0xa8, 0xa0, 0x21, 0x2a,
	0x14, 0xfa, 0x84, 0x59, 0x0d, 0x9b, 0xc8, 0x3f, 0x82, 0x2f, 0x6f, 0x6e, 0x66, 0x7a, 0xb6, 0x7e,
	0x58, 0xb0, 0xa4, 0x35, 0x6b, 0xf5, 0xfd, 0xc7, 0x89, 0xba, 0x34, 0xd2, 0xdf, 0xce, 0xc0, 0xb5,
	0x27, 0x82, 0x72, 0xd5, 0x13, 0x2c, 0x61, 0x03, 0x0c, 0x70, 0x3a, 0xe3, 0x37, 0xa0, 0xd9, 0xc5,
	0xf0, 0x50, 0x97, 0xcd, 0x13, 0xe4, 0x71, 0xca, 0xde, 0x8f, 0x14, 0xe3, 0x81, 0xc7, 0x82, 0x17,
	0x4a, 0xcb, 0x6b, 0x7a, 0xa3, 0x29, 0xd2, 0x82, 0xe5, 0x0e, 0x67, 0x8a, 0x51, 0xc5, 0x12, 0x34,
	0xa8, 0x86, 0x46, 0x8d, 0xa7, 0x53, 0x64, 0x97, 0x72, 0x1a, 0x60, 0x88, 0x5c, 0x19, 0xe4, 0x9c,
	0x41, 0x8e, 0xa5, 0xd3, 0x67, 0x79, 0x8e, 0x1a, 0xd0, 0xdc, 0xb4, 0x5a, 0x8b, 0x5e, 0x16, 0x95,
	0x5c, 0x78, 0x37, 0x03, 0xab, 0xb9, 0x01, 0xda, 0x8e, 0x69, 0xdf, 0xe2, 0xe5, 0xf4, 0x21, 0x01,
	0xe2, 0x61, 0x12, 0xbd, 0xc4, 0xfa, 0xa7, 0xa1, 0xd4, 0xf7, 0x83, 0x35, 0xe2, 0xbf, 0x51, 0x50,
	0xa3, 0xff, 0x85, 0x13, 0xf6, 0x99, 0x4e, 0x7c, 0xcd, 0x97, 0x51, 0x5b, 0x20, 0x9d, 0xce, 0x85,
	0x75, 0x68, 0xa4, 0x87, 0xe4, 0x4a, 0xb2, 0x28, 0xbf, 0xe9, 0xf6, 0xd9, 0x37, 0x7d, 0x76, 0xe2,
	0xa6, 0x97, 0x54, 0x7e, 0xb3, 0x60, 0x49, 0xeb, 0xbb, 0x88, 0xc5, 0x53, 0x9f, 0xcc, 0x9f, 0x36,
	0x2c, 0x1b, 0x89, 0xbd, 0x68, 0xc0, 0xfc, 0xd7, 0x53, 0x0f, 0x95, 0x39, 0xa6, 0x78, 0xb5, 0xc3,
	0xf8, 0x1c, 0x8b, 0xf2, 0x01, 0xac, 0x75, 0x19, 0x6f, 0xf7, 0x43, 0x26, 0x25, 0x8b, 0xb8, 0x1b,
	0x0b, 0x9a, 0x3f, 0xc2, 0xac, 0x57, 0x59, 0xd3, 0x1c, 0x7a, 0x3a, 0xc9, 0x69, 0x64, 0x9c, 0x8a,
	0x1a, 0xd9, 0x06, 0xe2, 0x32, 0xe9, 0xc7, 0x65, 0xc6, 0x9c, 0x66, 0x54, 0x54, 0xd2, 0x1e, 0xfb,
	0x28, 0xd8, 0x11, 0xf3, 0x75, 0x9c, 0x33, 0x9a, 0xa6, 0x47, 0x55, 0x8d, 0xdc, 0x81, 0x25, 0xb3,
	0x35, 0x72, 0xf4, 0xbc, 0x46, 0x8f, 0x65, 0x53, 0x5c, 0x47, 0xca, 0x18, 0x9f, 0xc5, 0x91, 0x88,
	0xc3, 0xdd, 0x38, 0x74, 0xc0, 0xe0, 0xca, 0xd9, 0x31, 0x9c, 0x8b, 0xdc, 0x59, 0x98, 0xc0, 0xb9,
	0xc8, 0xc9, 0x7d, 0x58, 0x2d, 0xf6, 0x50, 0x71, 0xe8, 0x55, 0x0d, 0xae, 0x2a, 0x55, 0x31, 0xd2,
	0xe3, 0x17, 0xab, 0x19, 0x2e, 0x96, 0xe7, 0xe7, 0x97, 0x0d, 0x2b, 0xd9, 0xe4, 0x5c, 0xc4, 0xa0,
	0xff, 0x1f, 0xa0, 0x7f, 0x6d, 0x80, 0x4e, 0x60, 0xd5, 0x45, 0xea, 0x2b, 0x96, 0xd4, 0xbf, 0x83,
	0x4a, 0x8d, 0x4f, 0x61, 0xcd, 0xe4, 0x8b, 0xf6, 0xf5, 0x0d, 0x6f, 0xa9, 0xf3, 0x7b, 0x0b, 0x48,
	0x7b, 0x30, 0x88, 0x4e, 0xd2, 0x2d, 0x5e, 0xf7, 0xda, 0x2d, 0x3e, 0x1d, 0xf6, 0xe8, 0xa7, 0xa3,
	0x24, 0xe8, 0xa3, 0x05, 0x6b, 0x85, 0x16, 0x2d, 0xad, 0xce, 0x8b, 0x7c, 0x1e, 0x49, 0x9f, 0x2c,
	0xb8, 0xee, 0x32, 0x49, 0xff, 0x26, 0x9b, 0x3e, 0x5b, 0x70, 0xa3, 0xd0, 0x32, 0x54, 0xf7, 0x87,
	0x9d, 0x3a, 0x6c, 0xe8, 0xbf, 0x68, 0x0f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x47, 0x7a, 0x46,
	0x0f, 0xeb, 0x0d, 0x00, 0x00,
}
