package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	packageName := os.Args[1]
	varName := os.Args[2]
	inFilename := os.Args[3]
	outFile := os.Args[4]

	inContent, err := ioutil.ReadFile(inFilename)
	if err != nil {
		panic(err)
	}

	out, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}

	out.Write([]byte(fmt.Sprintf("package %s\n\n", packageName)))
	out.Write([]byte(fmt.Sprintf("// Autogenerated from %s, do not edit \n\n", inFilename)))
	out.Write([]byte(fmt.Sprintf("const %s = `", varName)))
	out.Write(inContent)
	out.Write([]byte("`"))
}
